export const WS_EVENTS = {
  api: {
    capabilities: 'api.capabilities',
  },
  chat: {
    message: 'chat-message',
    messageUpdated: 'chat-message.updated',
    messageDeleted: 'chat-message.deleted',
    send: 'chat-send',
    edit: 'chat-edit',
    delete: 'chat-delete',
    history: 'chat-history',
    error: 'error',
    presenceContext: 'presence-context',
    presenceActivity: 'presence-activity',
  },
  presence: {
    update: 'presence-update',
  },
  auth: {
    login: 'auth.login',
    logout: 'auth.logout',
    refresh: 'auth.refresh',
    register: 'auth.register',
    loginOk: 'auth.login.ok',
    logoutOk: 'auth.logout.ok',
    refreshOk: 'auth.refresh.ok',
    registerOk: 'auth.register.ok',
  },
  users: {
    list: 'users.list',
    get: 'users.get',
  },
  social: {
    friendsList: 'social.friends.list',
    friendsRequests: 'social.friends.requests',
    friendsBlocked: 'social.friends.blocked',
    friendsRequest: 'social.friends.request',
    friendsAccept: 'social.friends.accept',
    friendsReject: 'social.friends.reject',
    friendsCancel: 'social.friends.cancel',
    friendsRemove: 'social.friends.remove',
    friendsBlock: 'social.friends.block',
    friendsUnblock: 'social.friends.unblock',
    profileGet: 'social.profile.get',
    profileUpdate: 'social.profile.update',
    userSearch: 'social.user.search',
    friendAccepted: 'social.friend.accepted',
    friendRequested: 'social.friend.requested',
    friendRejected: 'social.friend.rejected',
    friendConnected: 'social.friend.connected',
    friendDisconnected: 'social.friend.disconnected',
  },
  messaging: {
    conversation: 'messaging.conversation',
    messages: 'messaging.messages',
    send: 'messaging.send',
    delete: 'messaging.delete',
    restore: 'messaging.restore',
    purge: 'messaging.purge',
    search: 'messaging.search',
    markRead: 'messaging.markRead',
    messageSent: 'messaging.message',
    messageDeleted: 'messaging.deleted',
    messageRestored: 'messaging.restored',
    messagePurged: 'messaging.purged',
    user: 'messaging.user',
  },
  admin: {
    users: {
      list: 'admin.users.list',
      get: 'admin.users.get',
      ban: 'admin.users.ban',
      unban: 'admin.users.unban',
      delete: 'admin.users.delete',
      roles: 'admin.users.roles',
      rolesUpdated: 'admin.users.rolesUpdated',
    },
    games: {
      list: 'admin.games.list',
      setEnabled: 'admin.games.setEnabled',
      update: 'admin.games.update',
      reset: 'admin.games.reset',
      categories: 'admin.games.categories',
      categoryCreate: 'admin.games.category.create',
      categoryUpdate: 'admin.games.category.update',
      categoryAssign: 'admin.games.category.assign',
      categoryDelete: 'admin.games.category.delete',
    },
    roles: {
      list: 'admin.roles.list',
      definitions: 'admin.roles.definitions',
      create: 'admin.roles.create',
      update: 'admin.roles.update',
      delete: 'admin.roles.delete',
    },
    logs: {
      download: 'admin.logs.download',
    },
    broadcast: 'admin.broadcast',
    chat: {
      messages: 'admin.chat.messages',
      settingsGet: 'admin.chat.settings.get',
      settingsUpdate: 'admin.chat.settings.update',
      delete: 'admin.chat.delete',
      clear: 'admin.chat.clear',
      ban: 'admin.chat.ban',
      unban: 'admin.chat.unban',
    },
    rooms: {
      cleanup: 'admin.rooms.cleanup',
      list: 'admin.rooms.list',
      destroy: 'admin.rooms.destroy',
      settingsGet: 'admin.rooms.settings.get',
      settingsUpdate: 'admin.rooms.settings.update',
    },
    profile: {
      settingsGet: 'admin.profile.settings.get',
      settingsUpdate: 'admin.profile.settings.update',
    },
    stats: {
      resetAll: 'admin.stats.resetAll',
    },
    bots: {
      namesList: 'admin.bots.names.list',
      settingsGet: 'admin.bots.settings.get',
      settingsUpdate: 'admin.bots.settings.update',
      nameCreate: 'admin.bots.name.create',
      nameUpdate: 'admin.bots.name.update',
      nameDelete: 'admin.bots.name.delete',
    },
    perf: {
      snapshot: 'admin.perf.snapshot',
    },
    bugReports: {
      create: 'admin.bugReports.create',
      list: 'admin.bugReports.list',
      get: 'admin.bugReports.get',
      update: 'admin.bugReports.update',
      updateStatus: 'admin.bugReports.updateStatus',
      delete: 'admin.bugReports.delete',
      commentsList: 'admin.bugReports.comments.list',
      commentsAdd: 'admin.bugReports.comments.add',
    },
    quiz: {
      mnemo: {
        categories: 'admin.quiz.mnemo.categories',
        categoryCreate: 'admin.quiz.mnemo.category.create',
        categoryUpdate: 'admin.quiz.mnemo.category.update',
        categoryDelete: 'admin.quiz.mnemo.category.delete',
        questions: 'admin.quiz.mnemo.questions',
        questionCreate: 'admin.quiz.mnemo.question.create',
        questionUpdate: 'admin.quiz.mnemo.question.update',
        questionDelete: 'admin.quiz.mnemo.question.delete',
      },
    },
  },
  notify: {
    connected: 'notify.connected',
    counts: 'notify.counts',
    countsGet: 'notify.counts.get',
    inbox: {
      list: 'notify.inbox.list',
      delete: 'notify.inbox.delete',
      markRead: 'notify.inbox.markRead',
      snapshot: 'notify.inbox.snapshot',
      item: 'notify.inbox.item',
      removed: 'notify.inbox.removed',
      send: 'notify.admin_contact.send',
      reply: 'notify.admin_contact.reply',
      setHandled: 'notify.admin_contact.setHandled',
      setStatus: 'notify.admin_contact.setStatus',
      cycleStatus: 'notify.admin_contact.cycleStatus',
      threads: 'notify.admin_contact.threads',
      deleteThread: 'notify.admin_contact.deleteThread',
      sent: 'notify.admin_contact.sent',
      error: 'notify.admin_contact.error',
    },
  },
  clientUpdate: {
    available: 'client.update.available',
    required: 'client.update.required',
    imminent: 'client.update.imminent',
  },
  room: {
    restoreReady: 'rooms.restore.ready',
  },
  system: {
    serverDisconnect: 'server.disconnect',
  },
} as const;
