import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { PrimalisSetupService } from './setup/primalis-setup.service';
import { PrimalisActionService } from './actions/primalis-action.service';
import { PrimalisPresenterService } from './presenter/primalis-presenter.service';
import { PrimalisBotService } from './bots/primalis-bot.service';
export declare class PrimalisService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "primalis";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "LesQuatreVents";
    readonly displayName: string;
    readonly description = "Survivez \u00E0 la com\u00E8te : construisez votre tribu de dinosaures et nourrissez-la avant la catastrophe finale.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: PrimalisSetupService, actions: PrimalisActionService, presenter: PrimalisPresenterService, bots: PrimalisBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
