import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { AFondLesBallonsSetupService } from './setup/a-fond-les-ballons-setup.service';
import { AFondLesBallonsActionService } from './actions/a-fond-les-ballons-action.service';
import { AFondLesBallonsPresenterService } from './presenter/a-fond-les-ballons-presenter.service';
import { AFondLesBallonsBotService } from './bots/a-fond-les-ballons-bot.service';
export declare class AFondLesBallonsService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "a-fond-les-ballons";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "LesQuatreVents";
    readonly displayName: string;
    readonly description = "Course d\u00E9jant\u00E9e jusqu'\u00E0 la Grosse Noix Dor\u00E9e.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: AFondLesBallonsSetupService, actions: AFondLesBallonsActionService, presenter: AFondLesBallonsPresenterService, bots: AFondLesBallonsBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
