import { RoomService } from '../../../room/services/room.service';
import { GameCoreService } from '../../core/services/game-core.service';
import { GameSingleActionDto, GameStateResponse, GameStateWithActions } from '../dto/game-action.dto';
import { GameRegistryService } from './game-registry.service';
import type { GameStateEntity } from '../../core/entities/game-state.entity';
import { TurnLabelService } from '../../modules/turn/services/turn-label.service';
import { BotRunnerService } from '../../modules/bot/services/bot-runner.service';
import { BotSchedulerService } from '../../modules/bot/services/bot-scheduler.service';
import { BotSettingsService } from '../../modules/bot/services/bot-settings.service';
import { GameEngineStateStore } from './game-engine-state.store';
import { GameLoggerService } from '../../../common/services/game-logger.service';
import { GameStatsService } from '../../../stats/services/game-stats.service';
import { GridRenderService } from '../../modules/grid/services/grid-render.service';
type GameEndedOutcome = 'won' | 'lost' | 'draw' | 'unknown';
type GameEndedPayload = {
    roomId: number;
    gameType: string;
    status: 'finished';
    finishedAt: string;
    winnerPlayerId: number | null;
    outcomesByPlayerId: Record<string, GameEndedOutcome>;
    playersById: Record<string, string>;
    turnIndex: number | null;
};
export declare class GameEngineService {
    private readonly rooms;
    private readonly core;
    private readonly registry;
    private readonly turnLabel;
    private readonly botRunner;
    private readonly botScheduler;
    private readonly botSettings;
    private readonly gridRender;
    private readonly store;
    private readonly gameLogger;
    private readonly stats;
    private broadcaster?;
    private endedBroadcaster?;
    private readonly mutationQueue;
    private readonly exposedStateByUserCache;
    private static readonly MAX_ACTIONS_PER_MESSAGE;
    private static readonly MAX_ACTION_TYPE_LENGTH;
    private static readonly MAX_ACTION_PAYLOAD_BYTES;
    private static readonly MAX_MESSAGE_PAYLOAD_BYTES;
    private static readonly BOT_THINKING_TTL_MS;
    private static readonly FINISHED_STATE_GRACE_MS;
    private static nowMs;
    constructor(rooms: RoomService, core: GameCoreService, registry: GameRegistryService, turnLabel: TurnLabelService, botRunner: BotRunnerService, botScheduler: BotSchedulerService, botSettings: BotSettingsService, gridRender: GridRenderService, store: GameEngineStateStore, gameLogger: GameLoggerService, stats: GameStatsService);
    setBroadcaster(fn: (gameType: string, roomId: number, state: GameStateEntity) => void): void;
    setEndedBroadcaster(fn: (gameType: string, roomId: number, state: GameStateEntity, payload: GameEndedPayload) => void): void;
    getState(roomId: number, gameType: string): Promise<GameStateWithActions>;
    getStateForUser(roomId: number, gameType: string, userId: number): Promise<GameStateWithActions>;
    exposeStateForUser(state: GameStateEntity, gameType: string, userId: number): GameStateWithActions;
    handleKeyPress(roomId: number, gameType: string, userId: number, key: string): Promise<{
        kind: 'action';
        actions: GameSingleActionDto[];
    } | {
        kind: 'panel';
        panelId: string;
        message: string;
    } | {
        kind: 'room';
        op: 'reset' | 'start' | 'restart';
    } | null>;
    refreshAndBroadcast(roomId: number, gameType: string): Promise<void>;
    private attachShortcuts;
    private mergeCommonShortcuts;
    private getInternalState;
    applyActions(roomId: number, gameType: string, actions: GameSingleActionDto[], actorId: number | null, allowBotTurn?: boolean): Promise<GameStateResponse>;
    private applyActionsInternal;
    private toMetadata;
    private normalizeMetadataString;
    private parseMetadataNumber;
    private getMetadataObject;
    private normalizeWinnerMetadata;
    private normalizeUsernameForLog;
    private buildPlayersFromPayload;
    private normalizeActionType;
    private isDrawAction;
    private forceFinishedIfWinnerDetected;
    private deriveFinishedOutcomes;
    private buildEndedPayload;
    private tryReadWinnerId;
    private tryReadOutcomesByPlayerId;
    playBotTurn(roomId: number, gameType: string): Promise<GameStateWithActions>;
    private playBotTurnInternal;
    private enqueueMutation;
    private syncRosterForStartedRoom;
    exportInternalState(roomId: number, gameType: string): Promise<GameStateEntity | null>;
    restoreInternalState(roomId: number, gameType: string, state: GameStateEntity): Promise<void>;
    private isBotTurn;
    private getBotActorIdForState;
    private pendingSignature;
    private buildSystemTimerKey;
    private applySystemActions;
    private scheduleBotTurn;
    checkAccess(roomId: number, userId: number, ownerOnly?: boolean): Promise<void>;
    checkReadAccess(roomId: number, userId: number): Promise<void>;
    checkPlayAccess(roomId: number, userId: number): Promise<void>;
    private buildInitialState;
    private ensureRandomStarterAtGameStart;
    private appendFirstTurnAnnouncement;
    private buildKey;
    private isWithinFinishedGraceWindow;
    private scheduleFinishedRoomReset;
    private markBotThinking;
    private normalizeBotThinking;
    private validateActions;
    private shouldSilentlyIgnoreUnavailableAction;
    private isOutOfTurn;
    private isOutOfTurnMessage;
    private exposeState;
    private stripBoardAndGridIfNotStarted;
    private attachTurnLabel;
    private attachCurrentPlayerView;
    private appendBoardArrivalAnnouncements;
    private appendSkipTurnAnnouncements;
    private attachViewerContext;
    private attachUiDescriptors;
    private isRoomNotFound;
    private cleanupRoom;
    private static extractExtras;
    private static extractUi;
    private static extractPanels;
    private static extractPanelMessage;
}
export {};
