import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
export declare class TaxiExpressActionService {
    private readonly core;
    private readonly random;
    private readonly turns;
    private readonly deckPolicies;
    private static readonly TRIPS_TO_WIN;
    constructor(core: GameCoreService, random: RandomService, turns: TurnFlowService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleRoll;
    private ensureActiveClient;
    private ensureEventForPlayer;
    private incrementTrip;
    private setWinner;
    private dropActiveClient;
    private drawClientCard;
    private drawEventCard;
    private buildPathIndices;
    private setPlayerPosition;
    private replaceMeta;
    private getMeta;
    private findClient;
    private findEvent;
    private findTileIndexById;
    private getTileByIndex;
    private tileTitleById;
}
