import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { LesMainsActionService } from './actions/les-mains-de-la-terre-action.service';
import { LesMainsDeLaTerreBotService } from './bots/les-mains-de-la-terre-bot.service';
import { LesMainsPresenterService } from './presenter/les-mains-de-la-terre-presenter.service';
import { LesMainsSetupService } from './setup/les-mains-de-la-terre-setup.service';
export declare class LesMainsDeLaTerreService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType: "les-mains-de-la-terre";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "VentsDansants";
    readonly displayName: string;
    readonly description = "Compl\u00E9tez des familles de m\u00E9tiers tout en jouant des cartes sp\u00E9ciales d\u00E9boussolantes.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: LesMainsSetupService, actions: LesMainsActionService, presenter: LesMainsPresenterService, bots: LesMainsDeLaTerreBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
