namespace client_win.Modules.Admin.ViewModels;

public enum AdminNavResult
{
    Stay,
    Moved,
    Closed
}

internal enum AdminPage
{
    Root,
    StoryBook,
    Maintenance,
    MaintenanceBackend,
    MaintenanceSystemd,
    Rooms,
    RoomsJoinSilent,
    RoomsDestroy,
    Games,
    GameCategories,
    GameCategoryForm,
    GameCategoryAssign,
    GameActions,
    EditText,
    EditPlayers,
    Bots,
    BotNameActions,
    BotNameForm,
    BotSettingsForm,
    Roles,
    Users,
    UserActions,
    BanForm,
    UserChatBanForm,
    UsersProfile,
    UsersProfileBioSettings,
    Chat,
    ChatDay,
    ChatMessageActions,
    ChatBanForm,
    ChatSettings,
    Broadcast,
    ClientUpdates,
    Logs,
    RoleDefinitions,
    RoleDefinitionActions,
    RoleDefinitionForm,
    Perf,
    Sounds,
	SoundsAmbience,
	SoundsTable,
	SoundsGames,
	SoundsInvitations,
	SoundsConnection,
	SoundsChat,
	SoundsChatGeneral,
	SoundsChatTable,
	SoundsPrivateMessages,
	SoundsAdminContact,
    SoundsTableAmbience,
    SoundDetails,
    BugReports,
    BugReportsStatusReports,
    BugReportCreate,
    BugReportDetails,
    BugReportEdit,
    BugReportConsult,
    BugReportComments,
    BugReportCommentCreate,
    MnemoQuizCategories,
    MnemoQuizCategoryActions,
    MnemoQuizQuestions,
    MnemoQuizQuestionActions
}

public sealed record PermissionModuleDescriptor(string ModuleId, string DisplayName, string Description);
