# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.ws.host: '%env(string:APP_WS_HOST)%'
    app.ws.port: '%env(int:APP_WS_PORT)%'
    app.ws.push_secret: '%env(string:APP_WS_PUSH_SECRET)%'
    app.ws.push_url: '%env(string:APP_WS_PUSH_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Module\Game\Engine\GameEngineInterface:
            tags: ['app.game_engine']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Module\User\Api\CustomOpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\Module\User\Api\CustomOpenApiFactory.inner']

    App\Module\Game\Realtime\RoomRealtimePushHandler:
        arguments:
            $secret: '%app.ws.push_secret%'

    App\Module\Game\Engine\EngineRegistry:
        arguments:
            $engines: !tagged_iterator app.game_engine

    App\Module\Game\Realtime\Command\RealtimeServerCommand:
        tags: ['console.command']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
