import { compileJsonGame } from '../../../rules/public-api';
import {
  AuthoringError,
  authoringValueAt,
} from '../../../engine/runtime/contracts/authoring-error';
import { fixture, object } from './extension-diagnostic-fixture';
import { authoringProperty } from '../../../engine/runtime/contracts/authoring-diagnostics';
import { jsonEffectPacks } from '../../../rules/effect-packs/json-effect-pack-registry';

function effectArray(
  value: unknown,
  path: string,
): { effects: unknown[]; path: string } | undefined {
  if (!value || typeof value !== 'object') return undefined;
  if (Array.isArray(value)) {
    for (const [i, child] of value.entries()) {
      const found = effectArray(child, `${path}[${i}]`);
      if (found) return found;
    }
  } else {
    const record = object(value);
    if (Array.isArray(record.effects))
      return { effects: record.effects, path: `${path}.effects` };
    for (const [key, child] of Object.entries(record)) {
      const found = effectArray(child, authoringProperty(path, key));
      if (found) return found;
    }
  }
  return undefined;
}

const cardCases = jsonEffectPacks.flatMap((pack) => {
  const data = fixture(pack.documentKey);
  const found = effectArray(data.program, 'extensions[0].config');
  return found ? [{ key: pack.documentKey, ...data, ...found }] : [];
});
it('covers every pack that authors nested card effects', () => {
  expect(cardCases.length).toBeGreaterThanOrEqual(10);
});
it.each(cardCases)(
  '$key: preserves the source of a copied card effect',
  ({ source, manifest, effects, path }) => {
    effects.splice(0, effects.length, {
      kind: 'gain-resource',
      resource: 'missing',
      amount: 1,
    });
    expect(() => compileJsonGame(manifest, source)).toThrow(
      expect.objectContaining({
        code: 'GAME_AUTHORING_ERROR',
        path: `game.json.${path}[0].resource`,
        received: 'missing',
      }),
    );
  },
);

it('locates effects in a deck generated by the narrative extension', () => {
  const { source, program, manifest } = fixture('storyChallenge');
  const [key, cards] = Object.entries(object(program.decks))[0];
  if (!Array.isArray(cards)) throw new Error('Expected cards');
  object(cards[0]).effects = [
    { kind: 'gain-resource', resource: 'missing', amount: 1 },
  ];
  const path = `${authoringProperty('extensions[0].config.decks', key)}[0].effects[0].resource`;
  expect(() => compileJsonGame(manifest, source)).toThrow(
    expect.objectContaining({
      code: 'GAME_AUTHORING_ERROR',
      path: `game.json.${path}`,
      received: 'missing',
    }),
  );
});

it.each(['cards', 'initial', 'visibility', 'initialPhase', 'transitions'])(
  'locates judged-card %s failures at the component or phase that must change',
  (field) => {
    const { source, program, manifest } = fixture('judgedCards');
    if (!Array.isArray(source.components))
      throw new Error('Expected components');
    const components = source.components.map(object);
    const handIndex = components.findIndex(
      (c) => c.id === program.answerHandId,
    );
    const deckIndex = components.findIndex(
      (c) => c.id === program.answerDeckId,
    );
    let path: string;
    if (field === 'cards') {
      components[deckIndex].cards = ['unidentified'];
      path = `components[${deckIndex}].cards[0]`;
    } else if (field === 'initialPhase') {
      source.initialPhase = program.judgingPhase;
      path = 'initialPhase';
    } else if (field === 'transitions') {
      object(
        object(source.phases)[String(program.collectingPhase)],
      ).transitions = [];
      path = `phases.${String(program.collectingPhase)}.transitions`;
    } else {
      components[handIndex][field] = field === 'initial' ? 0 : 'public';
      path = `components[${handIndex}].${field}`;
    }
    expect(() => compileJsonGame(manifest, source)).toThrow(
      expect.objectContaining({
        code: 'GAME_AUTHORING_ERROR',
        path: `game.json.${path}`,
        received: authoringValueAt(source, path),
      }),
    );
  },
);

it('attributes incompatible mandatory extension objectives to the selected victory', () => {
  const { source, manifest } = fixture('grid');
  const other = fixture('anonymousVote');
  source.extensions = [
    {
      type: 'grid',
      config: object((source.extensions as unknown[])[0]).config,
    },
    { type: 'anonymousVote', config: other.program },
  ];
  try {
    compileJsonGame(manifest, source);
    throw new Error('Expected failure');
  } catch (error) {
    expect(error).toBeInstanceOf(AuthoringError);
    expect(error).toMatchObject({
      path: 'game.json.victory.kind',
      received: object(source.victory).kind,
      expected: expect.stringContaining(
        'program and victory required together',
      ),
    });
  }
});
