import { compileJsonGame } from '../../../rules/public-api';
import { fixture, object } from './extension-diagnostic-fixture';
import { authoringProperty } from '../../../engine/runtime/contracts/authoring-diagnostics';
import { jsonEffectPacks } from '../../../rules/effect-packs/json-effect-pack-registry';

function effectArray(
  value: unknown,
  path: string,
): { effects: unknown[]; path: string } | undefined {
  if (!value || typeof value !== 'object') return undefined;
  if (Array.isArray(value)) {
    for (const [i, child] of value.entries()) {
      const found = effectArray(child, `${path}[${i}]`);
      if (found) return found;
    }
  } else {
    const record = object(value);
    if (Array.isArray(record.effects))
      return { effects: record.effects, path: `${path}.effects` };
    for (const [key, child] of Object.entries(record)) {
      const found = effectArray(child, authoringProperty(path, key));
      if (found) return found;
    }
  }
  return undefined;
}

const cardCases = jsonEffectPacks.flatMap((pack) => {
  const data = fixture(pack.documentKey);
  const found = effectArray(data.program, 'extensions[0].config');
  return found ? [{ key: pack.documentKey, ...data, ...found }] : [];
});
it('covers every pack that authors nested card effects', () => {
  expect(cardCases.length).toBeGreaterThanOrEqual(10);
});
it.each(cardCases)(
  '$key: preserves the source of a copied card effect',
  ({ source, manifest, effects, path }) => {
    effects.splice(0, effects.length, {
      kind: 'gain-resource',
      resource: 'missing',
      amount: 1,
    });
    expect(() => compileJsonGame(manifest, source)).toThrow(
      expect.objectContaining({
        code: 'GAME_AUTHORING_ERROR',
        path: `game.json.${path}[0].resource`,
        received: 'missing',
      }),
    );
  },
);

it('locates effects in a deck generated by the narrative extension', () => {
  const { source, program, manifest } = fixture('storyChallenge');
  const [key, cards] = Object.entries(object(program.decks))[0];
  if (!Array.isArray(cards)) throw new Error('Expected cards');
  object(cards[0]).effects = [
    { kind: 'gain-resource', resource: 'missing', amount: 1 },
  ];
  const path = `${authoringProperty('extensions[0].config.decks', key)}[0].effects[0].resource`;
  expect(() => compileJsonGame(manifest, source)).toThrow(
    expect.objectContaining({
      code: 'GAME_AUTHORING_ERROR',
      path: `game.json.${path}`,
      received: 'missing',
    }),
  );
});
