import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
import { SetupFlowService } from '../../../../modules/setup-flow/services/setup-flow.service';
export declare class AFondLesBallonsActionService {
    private readonly core;
    private readonly random;
    private readonly deckPolicies;
    private readonly setupFlow;
    constructor(core: GameCoreService, random: RandomService, _turns: TurnFlowService, deckPolicies: DeckPoliciesService, setupFlow: SetupFlowService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleRoll;
    private handleSwapChooseTarget;
    private handleDraw;
    private handleChoosePawn;
    private advanceTurnWithSkipLogs;
    private appendTurnAnnouncement;
    private availablePawns;
    private moveBy;
    private applyLanding;
    private drawAndApplyLoufoque;
    private applyCardEffect;
    private applyBoutiqueWorstCard;
    private startSwapPending;
    private moveToNextType;
    private skipTurns;
    private grantTrapImmunity;
    private hasTrapImmunity;
    private decrementTrapImmunity;
    private drawLoufoque;
    private computeTarget;
    private getMeta;
    private pawnLabel;
    private compactTileLabel;
}
