import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { SetupFlowService } from '../../../../modules/setup-flow/services/setup-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { TurnPoliciesService } from '../../../../modules/turn-policies/services/turn-policies.service';
import { PromptPoliciesService } from '../../../../modules/prompt-policies/services/prompt-policies.service';
export declare class MinuitActionService {
    private readonly random;
    private readonly turns;
    private readonly core;
    private readonly setupFlow;
    private readonly deckPolicies;
    private readonly turnPolicies?;
    private readonly promptPolicies?;
    constructor(random: RandomService, turns: TurnFlowService, core: GameCoreService, setupFlow: SetupFlowService, deckPolicies: DeckPoliciesService, turnPolicies?: TurnPoliciesService | undefined, promptPolicies?: PromptPoliciesService | undefined);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private isBotLike;
    private hasPawnAssigned;
    private handleRoll;
    private handleDraw;
    private applyDrawCard;
    private handleAnswerQuiz;
    private handleChooseTarget;
    private ensurePawnSelection;
    private queuePawnSelection;
    private assignBotPawns;
    private handlePickPawn;
    private listPawnChoices;
    private listPawnChoiceEntries;
    private arePawnsEqual;
    private applyLanding;
    private applyCard;
    private formatCardEffect;
    private move;
    private setPos;
    private drawCard;
    private parseQuizCard;
    private otherPlayers;
    private findOccupant;
    private getMeta;
    private pawnLabel;
    private resolvePawnName;
    private pawnPossessiveLabel;
    private lowercaseFirst;
    private appendTurnAnnouncement;
    private getTurnPolicies;
    private getPromptPolicies;
    private restoreStarterAfterPawnSelection;
    private advanceTurnOrKeep;
}
