using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
using client_win.Core.Diagnostics;
using client_win.Modules.Shell.Services;

namespace client_win.Modules.Shell.Views;

/// <summary>
/// Content host that keeps the previous view alive until the new one is actually ready and focused.
/// This avoids NVDA announcing "indisponible" when focus lands on an element that is removed during a view swap.
/// </summary>
public partial class StableContentHost : UserControl
    , ICurrentContentRootProvider
{
    public static readonly DependencyProperty CurrentContentProperty =
        DependencyProperty.Register(
            nameof(CurrentContent),
            typeof(object),
            typeof(StableContentHost),
            new PropertyMetadata(null, OnCurrentContentChanged));

    public static readonly DependencyProperty PreviousContentProperty =
        DependencyProperty.Register(
            nameof(PreviousContent),
            typeof(object),
            typeof(StableContentHost),
            new PropertyMetadata(null));

    private const int FocusRetryMaxAttempts = 24;
    private static readonly TimeSpan FocusRetryInterval = TimeSpan.FromMilliseconds(125);

    private DispatcherTimer? _retryTimer;
    private int _retryRemaining;
    private int _transitionId;
    private DateTime _transitionStartedUtc;
    private bool _isTransitioning;

    public StableContentHost()
    {
        InitializeComponent();
        Loaded += (_, _) =>
        {
            // If CurrentContent is set before load, run an initial focus pass once the control is ready.
            BeginFocusPass();
        };
    }

    public object? CurrentContent
    {
        get => GetValue(CurrentContentProperty);
        set => SetValue(CurrentContentProperty, value);
    }

    public object? PreviousContent
    {
        get => GetValue(PreviousContentProperty);
        private set => SetValue(PreviousContentProperty, value);
    }

    /// <summary>
    /// Best-effort: return the current content root generated by the CurrentPresenter.
    /// Used by shell-wide focus recovery code.
    /// </summary>
    public DependencyObject? TryGetCurrentContentRoot()
        => TryGetPresenterRoot(CurrentPresenter);

    private static void OnCurrentContentChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        var host = (StableContentHost)d;
        host.OnCurrentContentChanged(oldContent: e.OldValue, newContent: e.NewValue);
    }

    private void OnCurrentContentChanged(object? oldContent, object? newContent)
    {
        using var _ = PerfTrace.Measure($"nav.swap {(newContent?.GetType().Name ?? "<null>")}");
        _transitionId = unchecked(_transitionId + 1);
        _transitionStartedUtc = DateTime.UtcNow;

        // Keep the old view alive behind the new one until focus successfully lands in the new view.
        PreviousContent = oldContent;
        _isTransitioning = oldContent != null;
        ApplyPresenterZOrder();

        BeginFocusPass();
    }

    private void BeginFocusPass()
    {
        using var _ = PerfTrace.Measure("nav.focusPass");
        if (!IsLoaded)
        {
            return;
        }

        _retryRemaining = FocusRetryMaxAttempts;
        ApplyPresenterZOrder();

        // Park focus on a stable element before anything is removed.
        try
        {
            var win = Window.GetWindow(this) ?? Application.Current?.MainWindow;
            if (_isTransitioning && PreviousContent != null)
            {
                FocusParking.ForcePark(win);
            }
            else
            {
                FocusParking.ParkIfNeeded(win);
            }
        }
        catch
        {
            /* ignore */
        }

        // After parking focus, re-evaluate z-order immediately so we don't keep the previous view on top
        // longer than necessary (perceived latency).
        ApplyPresenterZOrder();

        Dispatcher.BeginInvoke((Action)(() => TryFocusAndMaybeFinalize()), DispatcherPriority.Loaded);
        Dispatcher.BeginInvoke((Action)(() => TryFocusAndMaybeFinalize()), DispatcherPriority.ApplicationIdle);

        EnsureRetryTimer();
    }

    private void EnsureRetryTimer()
    {
        if (_retryTimer == null)
        {
            _retryTimer = new DispatcherTimer(DispatcherPriority.ApplicationIdle, Dispatcher)
            {
                Interval = FocusRetryInterval
            };
            _retryTimer.Tick += (_, _) => Retry();
        }

        _retryTimer.Interval = FocusRetryInterval;
        _retryTimer.Start();
    }

    private void Retry()
    {
        if (_retryRemaining <= 0)
        {
            try { _retryTimer?.Stop(); } catch { /* ignore */ }
            // As a last resort, remove the previous view while keeping focus on something stable.
            // This avoids leaving the old view permanently alive.
            TryForceFinalizeAfterTimeout();
            return;
        }

        _retryRemaining--;
        if (TryFocusAndMaybeFinalize())
        {
            try { _retryTimer?.Stop(); } catch { /* ignore */ }
        }
    }

    private bool TryFocusAndMaybeFinalize()
    {
        try
        {
            var window = Window.GetWindow(this) ?? Application.Current?.MainWindow;
            if (window != null && !window.IsActive)
            {
                return false;
            }

            // Attempt to move focus into the new view.
            if (TryFocusCurrent())
            {
                FinalizeTransitionIfSafe();
                return true;
            }

            FinalizeTransitionIfSafe();
            return false;
        }
        catch
        {
            return false;
        }
    }

    private void FinalizeTransitionIfSafe()
    {
        if (PreviousContent == null)
        {
            return;
        }

        var currentRoot = TryGetPresenterRoot(CurrentPresenter);
        if (currentRoot != null && IsFocusWithin(currentRoot))
        {
            _isTransitioning = false;
            ApplyPresenterZOrder();
            PreviousContent = null;
            return;
        }

        // If focus is not in the previous view anymore, we can drop it.
        var previousRoot = TryGetPresenterRoot(PreviousPresenter);
        if (previousRoot == null || !IsFocusWithin(previousRoot))
        {
            _isTransitioning = false;
            ApplyPresenterZOrder();
            PreviousContent = null;
        }
    }

    private void TryForceFinalizeAfterTimeout()
    {
        if (PreviousContent == null)
        {
            return;
        }

        // Wait a bit: some views populate async and will only become focusable later.
        if ((DateTime.UtcNow - _transitionStartedUtc) < TimeSpan.FromSeconds(3))
        {
            _retryRemaining = Math.Max(_retryRemaining, 1);
            EnsureRetryTimer();
            return;
        }

        try
        {
            // If focus is still within the previous view, park it to the window before removing it.
            var previousRoot = TryGetPresenterRoot(PreviousPresenter);
            if (previousRoot != null && IsFocusWithin(previousRoot))
            {
                try { FocusParking.ForcePark(Window.GetWindow(this) ?? Application.Current?.MainWindow); } catch { /* ignore */ }
            }
        }
        catch
        {
            // ignore
        }
        finally
        {
            _isTransitioning = false;
            ApplyPresenterZOrder();
            PreviousContent = null;
        }
    }

    private void ApplyPresenterZOrder()
    {
        try
        {
            // NVDA + UX:
            // - If the old focused element becomes fully obscured while still focused, NVDA can announce
            //   "non disponible". Keep the previous view on top ONLY while focus is still within it.
            // - Otherwise, show the new view immediately to avoid perceived navigation latency.
            if (_isTransitioning && PreviousContent != null)
            {
                var previousRoot = TryGetPresenterRoot(PreviousPresenter);
                var keepPreviousFront = previousRoot != null && IsFocusWithin(previousRoot);
                Panel.SetZIndex(PreviousPresenter, keepPreviousFront ? 1 : 0);
                Panel.SetZIndex(CurrentPresenter, keepPreviousFront ? 0 : 1);
                return;
            }

            Panel.SetZIndex(PreviousPresenter, 0);
            Panel.SetZIndex(CurrentPresenter, 1);
        }
        catch
        {
            // best-effort
        }
    }

    private bool TryFocusCurrent()
    {
        using var _ = PerfTrace.Measure("nav.tryFocusCurrent");
        var root = TryGetPresenterRoot(CurrentPresenter);
        if (root == null)
        {
            return false;
        }

        if (PresentationSource.FromDependencyObject(root) == null)
        {
            return false;
        }

        if (root is IInitialFocusTarget focusTarget)
        {
            if (!IsFocusWithin(root))
            {
                try { focusTarget.RequestInitialFocus(); } catch { /* ignore */ }
            }
            if (IsFocusWithin(root))
            {
                return true;
            }

            // IMPORTANT (perf): if a view provides a focus target, don't deep-scan the visual tree on each retry.
            // Deep scans can be expensive and may freeze the UI on slower machines during navigation.
            return false;
        }

        if (FindFirstFocusable(root) is IInputElement target)
        {
            try { (target as UIElement)?.Focus(); } catch { /* ignore */ }
            try { Keyboard.Focus(target); } catch { /* ignore */ }
            return IsFocusWithin(root);
        }

        return false;
    }

    private static DependencyObject? TryGetPresenterRoot(FrameworkElement presenter)
    {
        try
        {
            // ContentPresenter creates a visual child for the DataTemplate root when ready.
            var count = VisualTreeHelper.GetChildrenCount(presenter);
            if (count <= 0)
            {
                return null;
            }
            return VisualTreeHelper.GetChild(presenter, 0);
        }
        catch
        {
            return null;
        }
    }

    private static DependencyObject? FindFirstFocusable(DependencyObject root)
    {
        try
        {
            if (root is Control c &&
                c.IsVisible &&
                c.IsEnabled &&
                c.IsHitTestVisible &&
                (c.Focusable || KeyboardNavigation.GetIsTabStop(c)))
            {
                return c;
            }

            if (root is UIElement u &&
                u.IsVisible &&
                u.IsEnabled &&
                u.IsHitTestVisible &&
                u.Focusable)
            {
                return u;
            }

            var count = VisualTreeHelper.GetChildrenCount(root);
            for (var i = 0; i < count; i++)
            {
                var child = VisualTreeHelper.GetChild(root, i);
                if (child == null) continue;
                var found = FindFirstFocusable(child);
                if (found != null) return found;
            }
        }
        catch
        {
            // ignore
        }

        return null;
    }

    private static bool IsFocusWithin(DependencyObject root)
    {
        var focused = Keyboard.FocusedElement as DependencyObject;
        if (focused == null)
        {
            return false;
        }

        for (DependencyObject? current = focused; current != null; current = GetParent(current))
        {
            if (ReferenceEquals(current, root))
            {
                return true;
            }
        }
        return false;
    }

    private static DependencyObject? GetParent(DependencyObject current)
    {
        try
        {
            if (current is Visual || current is System.Windows.Media.Media3D.Visual3D)
            {
                return VisualTreeHelper.GetParent(current);
            }
        }
        catch
        {
            // ignore
        }

        if (current is FrameworkElement fe)
        {
            return fe.Parent ?? fe.TemplatedParent;
        }

        return LogicalTreeHelper.GetParent(current);
    }
}
