import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { RandomService } from '../../../../modules/random/services/random.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { SetupFlowService } from '../../../../modules/setup-flow/services/setup-flow.service';
import { FouleesFantastiquesSetupService } from '../setup/foulees-fantastiques-setup.service';
export declare class FouleesFantastiquesActionService {
    private readonly random;
    private readonly turns;
    private readonly core;
    private readonly setup;
    private readonly setupFlow;
    constructor(random: RandomService, turns: TurnFlowService, core: GameCoreService, setup: FouleesFantastiquesSetupService, setupFlow: SetupFlowService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private ensureFamilyPending;
    private handleChooseFamily;
    private handleRoll;
    private handleMovePawn;
    private computeMoves;
    private buildOpponentTrackIndex;
    private isBlockedByOpponentOnPath;
    private findBlockingOpponent;
    private applyMove;
    private applyCapture;
    private endTurn;
    private appendTurnAnnouncement;
    private appendLogOnce;
    private isWinner;
    private describeProgress;
    private pawnLabel;
    private pawnOwnedLabel;
    private habitatLabel;
    private fromHabitat;
}
