namespace client_win.Modules.Audio.Models;

public enum SoundId
{
    ClientOpened,
    ClientConnected,
    ClientDisconnected,
    ClientUpdateWarning,
    MainMenuMusic,
    TavernAmbience,
    TavernOpened,
    DiceRolled,
    ChatMessageSent,
    ChatMessageReceived,
    TableChatMessageSent,
    TableChatMessageReceived,
    PrivateMessageSent,
    PrivateMessageReceived,
    FriendConnected,
    FriendDisconnected,
    FriendInvitationSent,
    FriendInvitationReceived,
    GameVictory,
    GameDefeat,
    InvitationSent,
    InvitationReceived,
    AdminContactSent,
    AdminContactReceived,
    BugReportCommentReceived,
    RoomOpened,
    RoomJoined,
    RoomExit,
    PawnPicked,
    PawnPlacedSelf,
    PawnPlacedOpponent,
    WallPlacedSelf,
    WallPlacedOpponent,
}
