import { OnModuleInit } from '@nestjs/common';
import { WsRouteRegistry } from '../../common/ws/ws-route-registry.service';
import { AdminRoomsWsHandler } from './admin-rooms-ws.handler';
import { AdminChatWsHandler } from './admin-chat-ws.handler';
import { AdminUsersWsHandler } from './admin-users-ws.handler';
import { AdminGamesWsHandler } from './admin-games-ws.handler';
import { AdminBotsWsHandler } from './admin-bots-ws.handler';
import { AdminRolesWsHandler } from './admin-roles-ws.handler';
import { AdminLogsWsHandler } from './admin-logs-ws.handler';
import { AdminBroadcastWsHandler } from './admin-broadcast-ws.handler';
import { AdminClientUpdatesWsHandler } from './admin-client-updates-ws.handler';
import { AdminPerfWsHandler } from './admin-perf-ws.handler';
import { AdminProfileWsHandler } from './admin-profile-ws.handler';
import { AdminBugReportsWsHandler } from './admin-bug-reports-ws.handler';
import { AdminBugReportCommentsWsHandler } from './admin-bug-report-comments-ws.handler';
import { AdminStatsWsHandler } from './admin-stats-ws.handler';
import { AdminMnemoQuizWsHandler } from './admin-mnemo-quiz-ws.handler';
export declare class AdminWsRegistrar implements OnModuleInit {
    private readonly registry;
    private readonly rooms;
    private readonly chat;
    private readonly users;
    private readonly games;
    private readonly bots;
    private readonly roles;
    private readonly logs;
    private readonly broadcast;
    private readonly clientUpdates;
    private readonly perf;
    private readonly profile;
    private readonly bugReports;
    private readonly bugReportComments;
    private readonly stats;
    private readonly mnemoQuiz;
    constructor(registry: WsRouteRegistry, rooms: AdminRoomsWsHandler, chat: AdminChatWsHandler, users: AdminUsersWsHandler, games: AdminGamesWsHandler, bots: AdminBotsWsHandler, roles: AdminRolesWsHandler, logs: AdminLogsWsHandler, broadcast: AdminBroadcastWsHandler, clientUpdates: AdminClientUpdatesWsHandler, perf: AdminPerfWsHandler, profile: AdminProfileWsHandler, bugReports: AdminBugReportsWsHandler, bugReportComments: AdminBugReportCommentsWsHandler, stats: AdminStatsWsHandler, mnemoQuiz: AdminMnemoQuizWsHandler);
    onModuleInit(): void;
}
