import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { JeuOieActionService } from './actions/jeu-oie-action.service';
import { JeuOiePhaseService } from './phases/jeu-oie-phase.service';
import { JeuOiePresenterService } from './presenter/jeu-oie-presenter.service';
import { JeuOieSetupService } from './setup/jeu-oie-setup.service';
import { JeuOieBotService } from './bots/jeu-oie-bot.service';
export declare class JeuOieService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly phases;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "jeu-oie";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "Les Vents Sacr\u00E9s";
    readonly displayName: string;
    readonly description = "Le jeu de l'oie (course sur 63 cases).";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: JeuOieSetupService, actions: JeuOieActionService, phases: JeuOiePhaseService, presenter: JeuOiePresenterService, bots: JeuOieBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
