import { OnGatewayConnection, OnGatewayDisconnect } from '@nestjs/websockets';
import { Server, WebSocket } from 'ws';
import { RoomService } from '../services/room.service';
import { BotService } from '../../bot/services/bot.service';
import { WsJwtAuthService } from '../../common/ws/ws-jwt-auth.service';
import { CatalogService } from '../../catalog/services/catalog.service';
import { PerfMetricsService } from '../../common/services/perf-metrics.service';
import { RoomInviteService } from '../services/room-invite.service';
import { ClientUpdatesService } from '../../client-updates/services/client-updates.service';
import { WsTicketAuthService } from '../../common/ws/ws-ticket-auth.service';
import { RoomRealtimeTrackerService } from '../services/room-realtime-tracker.service';
export declare class RoomGateway implements OnGatewayConnection<WebSocket>, OnGatewayDisconnect<WebSocket> {
    private readonly roomsService;
    private readonly botService;
    private readonly auth;
    private readonly catalog;
    private readonly perf;
    private readonly invites;
    private readonly clientUpdates;
    private readonly wsTickets;
    private readonly realtimeTracker;
    server: Server<WebSocket>;
    private readonly clients;
    private readonly rooms;
    private readonly silentRooms;
    private readonly logger;
    private readonly heartbeats;
    private readonly lastPong;
    private readonly pingIntervalMs;
    private readonly lastChatSentAt;
    private readonly messageQueueByClient;
    private readonly roomChat;
    private readonly roomChatLimit;
    private readonly chatCooldownMs;
    private readonly chatMaxLength;
    private readonly lastRoomStatusByRoomId;
    private readonly participantDisconnectGraceMs;
    private readonly pendingParticipantLeaves;
    constructor(roomsService: RoomService, botService: BotService, auth: WsJwtAuthService, catalog: CatalogService, perf: PerfMetricsService, invites: RoomInviteService, clientUpdates: ClientUpdatesService, wsTickets: WsTicketAuthService, realtimeTracker: RoomRealtimeTrackerService);
    private forceDisconnectRoomClients;
    handleConnection(client: WebSocket, ...args: any[]): Promise<void>;
    handleDisconnect(client: WebSocket): Promise<void>;
    handleMessage(client: WebSocket, raw: any): Promise<void>;
    private enqueueClientMessage;
    private sendRoomState;
    private applySpectators;
    private broadcastRoomPayload;
    private tryUpdateRoomPayload;
    private sendRoomStateToClient;
    private broadcast;
    private sendError;
    private safeSend;
    private decode;
    private handleCommand;
    private sendChatHistoryToClient;
    private getRoomChatState;
    private normalizeChatMessage;
    private isRoomChatEnabled;
    private handleChatHistory;
    private handleChatSend;
    private extractTraceMeta;
    private handleRoomInfo;
    private handleRoomLeave;
    private handleRoomStart;
    private handleRoomReset;
    private promoteConnectedSpectatorsToParticipants;
    private handleTogglePrivacy;
    private handleBotAdd;
    private handleBotRemove;
    private handleSetRole;
    private handleRoomCreate;
    private handleRoomJoin;
    private leavePreviousRoomOnSwitch;
    private handleKickOrBan;
    private handleSetOwner;
    private forceDisconnectUser;
    private isAdmin;
    private hasUserConnections;
    private handleSetAmbience;
    private buildParticipantLeaveKey;
    private clearPendingParticipantLeave;
    private scheduleDelayedParticipantLeave;
    private canSpectate;
}
