import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { SetupFlowService } from '../../../../modules/setup-flow/services/setup-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { TurnPoliciesService } from '../../../../modules/turn-policies/services/turn-policies.service';
import { PromptPoliciesService } from '../../../../modules/prompt-policies/services/prompt-policies.service';
export declare class CatPattesActionService {
    private readonly core;
    private readonly turns;
    private readonly setupFlow;
    private readonly deckPolicies;
    private readonly random;
    private readonly turnPolicies?;
    constructor(core: GameCoreService, turns: TurnFlowService, setupFlow: SetupFlowService, deckPolicies: DeckPoliciesService, random: RandomService, turnPolicies?: TurnPoliciesService | undefined, _promptPolicies?: PromptPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleChoosePawn;
    private handleDraw;
    private handleDiscard;
    private handlePlayCard;
    private playPattes;
    private computeRoundPoints;
    private playObstacle;
    private playParade;
    private playBot;
    private clearDrawn;
    private drawForPlayer;
    private drawOneCard;
    private removeCardFromHand;
    private addCardToDiscard;
    private getMeta;
    private setMeta;
    private ensurePawnSelectionPrompt;
    private getTurnPolicies;
    private assignMissingBotPawns;
    private isBotLike;
    private toPlayerId;
    private samePlayerId;
}
