import { GameCoreService } from '../../../core/services/game-core.service';
import { GameStateEntity } from '../../../core/entities/game-state.entity';
import { GameSingleActionDto } from '../../../engine/dto/game-action.dto';
import { GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import { TurnService } from '../../../modules/turn/services/turn.service';
import { DeckPoolService } from '../../../modules/cards/services/deck-pool.service';
import { BoardMovementService } from '../../../modules/board/services/board-movement.service';
import { TileEffectRegistryService } from '../../../modules/effects/services/tile-effect-registry.service';
import { TurnActionsService } from '../../../modules/turn/services/turn-actions.service';
import { StandEffectRegistryService } from '../../../modules/effects/services/stand-effect-registry.service';
import { ActionResolverService } from '../../../modules/action-resolver/services/action-resolver.service';
import { TurnStatusService } from '../../../modules/turn/services/turn-status.service';
import { QuizRunnerService } from '../../../modules/quiz/services/quiz-runner.service';
import { VictoryService } from '../../../modules/victory/services/victory.service';
import { BotRunnerService } from '../../../modules/bot/services/bot-runner.service';
import { ActionLogService } from '../../../modules/actionlog/services/action-log.service';
import { PanierExpressMetadata, PanierExpressTile } from './model/panier-express-state.entity';
import { PanierExpressSetupService } from './setup/panier-express-setup.service';
import { PanierExpressDrawService } from './actions/panier-express-draw.service';
import { PanierExpressQuizService } from './actions/panier-express-quiz.service';
import { PanierExpressExchangeService } from './actions/panier-express-exchange.service';
import { PanierExpressUtils } from './model/panier-express-utils.service';
import { PanierExpressBotService } from './bots/panier-express-bot.service';
import { PanierExpressPhaseService } from './phases/panier-express-phase.service';
import { PanierExpressPresenterService } from './presenter/panier-express-presenter.service';
import { RandomService } from '../../../modules/random/services/random.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
export declare class PanierExpressService extends AbstractGameService {
    private readonly core;
    private readonly deckPool;
    private readonly movement;
    private readonly tileRegistry;
    private readonly standEffects;
    private readonly resolver;
    private readonly turnStatus;
    private readonly actionLogSvc;
    private readonly setup;
    private readonly drawSvc;
    private readonly quizSvc;
    private readonly quizRunner;
    private readonly exchangeSvc;
    private readonly utils;
    private readonly bots;
    private readonly phaseFlow;
    private readonly presenter;
    private readonly random;
    readonly gameType = "panier-express";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "LesQuatreVents";
    readonly displayName = "Panier Express";
    readonly description = "Course au march\u00E9 : compl\u00E9ter sa liste puis revenir pile sur la case d\u00E9part.";
    readonly minPlayers = 2;
    readonly maxPlayers = 10;
    private static readonly SHOPPING_LIST_SIZE;
    constructor(registry: GameRegistryService, core: GameCoreService, _turns: TurnService, deckPool: DeckPoolService, movement: BoardMovementService, tileRegistry: TileEffectRegistryService<GameStateEntity, {
        playerId: number;
        tile: PanierExpressTile;
    }>, _turnActions: TurnActionsService, standEffects: StandEffectRegistryService<GameStateEntity>, resolver: ActionResolverService, turnStatus: TurnStatusService, _victory: VictoryService, _botRunner: BotRunnerService, actionLogSvc: ActionLogService, setup: PanierExpressSetupService, drawSvc: PanierExpressDrawService, quizSvc: PanierExpressQuizService, quizRunner: QuizRunnerService, exchangeSvc: PanierExpressExchangeService, utils: PanierExpressUtils, bots: PanierExpressBotService, phaseFlow: PanierExpressPhaseService, presenter: PanierExpressPresenterService, random: RandomService);
    onModuleInit(): void;
    exposeState(state: GameStateEntity): GameStateWithActions;
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<PanierExpressMetadata>): GameShortcutHint[];
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private dispatchAction;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    private buildMetadata;
    private standIds;
    private buildTiles;
    private ensureMetadata;
    private mergeMetadataWithDefaults;
    private hydrateMetadataCollections;
    private ensurePlayerLaps;
    private mergeDecks;
    private mergeStatuses;
    private ensurePlayerPositions;
    private ensureQuizOutcome;
    private assignBotPawns;
    private queuePawnSelection;
    private ensureStarted;
    private finalizeStarterAfterPawnSelection;
    private handleRoll;
    private handleDraw;
    private startDrawPending;
    private queueCourseDraws;
    private advanceAfterDraw;
    private movePlayer;
    private tileLabel;
    private standLabel;
    private resolveTile;
    private registerTileHandlers;
    private applyMerchantRequest;
    private registerStandHandlers;
    private applyEvent;
    private applyExchange;
    private handleExchangeChooseTarget;
    private handleExchangeChooseGive;
    private handleExchangeAccept;
    private handleExchangeRefuse;
    private handleMerchantRequestAccept;
    private handleMerchantRequestRefuse;
    private handleSkipTurn;
    private handleChoosePawn;
    private handlePickChoice;
    private applyQuiz;
    private handleAnswerQuiz;
    private applyMoveDelta;
    private applyMoveChoice;
    private applyMoveToStandChoice;
    private applyWeatherBack;
    private applyMoveToNextStand;
    private applySkipTurnTile;
    private removeIngredientFromInventory;
    private addCourseToDiscards;
    private drawFromPool;
    private appendActionLog;
    private getMetadataRecord;
    private getPawnText;
    private getPlayers;
    private getActorIdFromAction;
    private getPendingRecord;
    private getMetadata;
    private toStringArray;
    private listKey;
    private buildShoppingList;
}
