import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { ToutPresDeMamanActionService } from './actions/tout-pres-de-maman-action.service';
import { ToutPresDeMamanPresenterService } from './presenter/tout-pres-de-maman-presenter.service';
import { ToutPresDeMamanSetupService } from './setup/tout-pres-de-maman-setup.service';
import { ToutPresDeMamanBotService } from './bots/tout-pres-de-maman-bot.service';
export declare class ToutPresDeMamanService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType: "tout-pres-de-maman";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "LesQuatreVents";
    readonly displayName: string;
    readonly description = "Guide votre b\u00E9b\u00E9 marsupial jusqu\u2019\u00E0 maman avec au moins trois jetons eucalyptus.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: ToutPresDeMamanSetupService, actions: ToutPresDeMamanActionService, presenter: ToutPresDeMamanPresenterService, bots: ToutPresDeMamanBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
