app.name=Les mondes de Lilas
network.http.base=https://api.lilas.hociatec.fr/api/
network.ws.url=wss://ws.lilas.hociatec.fr/ws
network.ws.presence=wss://ws.lilas.hociatec.fr/presence
app.version=1.0.9
updates.check.url=https://api.lilas.hociatec.fr/client/version
updates.root.dir=.
updates.auth.token=7e0b7da0b61a4c2cb4c6373dd5d5952c
# updates.signature.publicKey=./config/update-public.pem
# updates.signature.algorithm=SHA256withRSA

