network.http.base=https://hociatec.fr/api/
network.ws.url=wss://ws.hociatec.fr/ws
network.ws.presence=wss://ws.hociatec.fr/presence
app.version=1.0.0-SNAPSHOT
updates.check.url=https://hociatec.fr/client/version
