app.name=Les mondes de Lilas
network.http.base=https://hociatec.fr/api/
network.ws.url=wss://hociatec.fr/ws
network.ws.presence=wss://hociatec.fr/presence
app.version=1.0.5
updates.check.url=https://hociatec.fr/client/version
updates.root.dir=.
updates.auth.token=7e0b7da0b61a4c2cb4c6373dd5d5952c
