import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
export declare class LesMainsActionService {
    private readonly core;
    private readonly turns;
    private readonly random;
    private readonly deckPolicies;
    constructor(core: GameCoreService, turns: TurnFlowService, random: RandomService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleRequestCard;
    private drawCards;
    private applySpecialCard;
    private executeVoyage;
    private executeMetierDisparu;
    private executeFormationExpress;
    private executeGreveMondiale;
    private executeBoussolePerdue;
    private executePassation;
    private executeFete;
    private completeFamilyIfNeeded;
    private transferCard;
    private addCardToHand;
    private drawOneCard;
    private pickIndex;
    private shuffleWithMeta;
    private clearFreeRequest;
    private maybeFinishGame;
    private determineLeader;
    private getMeta;
    private setMeta;
    private getPlayerIds;
}
