import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { SetupFlowService } from '../../../../modules/setup-flow/services/setup-flow.service';
import { BoardEffectsPoliciesService } from '../../../../modules/board-effects-policies/services/board-effects-policies.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
export declare class FrousseActionService {
    private readonly random;
    private readonly turns;
    private readonly core;
    private readonly setupFlow;
    private readonly boardEffects;
    private readonly deckPolicies;
    constructor(random: RandomService, turns: TurnFlowService, core: GameCoreService, setupFlow: SetupFlowService, boardEffects: BoardEffectsPoliciesService, deckPolicies: DeckPoliciesService);
    private advanceTurnWithAnnouncement;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleChoosePawn;
    private ensurePawnSelection;
    private handleRoll;
    private handleChooseTarget;
    private handleDraw;
    private applyLanding;
    private applyDrawCard;
    private applyCard;
    private roll;
    private formatRollLabel;
    private move;
    private setPos;
    private drawCard;
    private otherPlayers;
    private otherPlayerIds;
    private getMeta;
    private pawnLabel;
    private pawnPossessiveLabel;
    private lowercaseFirst;
    private finalizeStarterAfterPawnSelection;
}
