import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
export declare class EntreRitesActionService {
    private readonly core;
    private readonly turns;
    private readonly deckPolicies;
    constructor(core: GameCoreService, turns: TurnFlowService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleAskCard;
    private handlePass;
    private advanceTurn;
    private transferCard;
    private drawCardForPlayer;
    private drawSingleCard;
    private handleDrawnCard;
    private handleSpecialEffect;
    private effectDrawTwo;
    private effectDrawAndTrigger;
    private effectCollectFromOthers;
    private effectTakeFromDiscard;
    private effectMuteSpecials;
    private effectSwapHands;
    private effectFreeFamily;
    private effectReshuffleCycle;
    private effectPeaceTurns;
    private effectRevealAndSteal;
    private discardOneCard;
    private discardCard;
    private isSilenced;
    private rebuildCollections;
    private checkVictory;
    private findWinner;
    private recordSpecial;
    private drawOneCard;
    private addCardToHand;
    private removeCardFromHand;
    private addCardToDiscard;
    private setMeta;
    private getMeta;
}
