import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { OlympiaActionService } from './actions/olympia-action.service';
import { OlympiaPresenterService } from './presenter/olympia-presenter.service';
import { OlympiaSetupService } from './setup/olympia-setup.service';
import { OlympiaBotService } from './bots/olympia-bot.service';
export declare class OlympiaService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "olympia";
    readonly category = "JeuxDeCartes";
    readonly subcategory = "VentsDansants";
    readonly displayName: string;
    readonly description = "Accumulez un maximum de prestige divin en jouant vos h\u00E9ros, exploits, cr\u00E9atures, actions, attaques et \u00E9v\u00E9nements.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: OlympiaSetupService, actions: OlympiaActionService, presenter: OlympiaPresenterService, bots: OlympiaBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
