import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { RandomService } from '../../../../modules/random/services/random.service';
export declare class ZigEtZagActionService {
    private readonly core;
    private readonly turns;
    private readonly random;
    constructor(core: GameCoreService, turns: TurnFlowService, random: RandomService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleSelectCard;
    private handleDrawCard;
    private finalizeStage;
    private handleSelectionCompletion;
    private prepareBattle;
    private promoteToBattleFaceUp;
    private resolveBattle;
    private finishRound;
    private logRound;
    private appendRevealLogs;
    private appendCollectiveRevealLog;
    private hasSelectionJoker;
    private setCurrentPlayer;
    private setCurrentPlayerWithAnnouncement;
    private setRoundState;
    private getMeta;
    private ensureRoundState;
    private normalizeRoundState;
    private pickNextCurrentPlayerId;
    private recordPlayedCard;
    private playCardWithId;
    private isWaitingPlayer;
    private normalizeWaitingPlayers;
    private collectTableCards;
    private evaluateFaceUpPlays;
    private addCardsToWinner;
    private applyWinnerCaptureBonus;
    private detectWinner;
    private formatCardLabel;
    private getActorId;
}
