import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
export declare class ToutPresDeMamanActionService {
    private readonly core;
    private readonly random;
    private readonly turns;
    private readonly deckPolicies;
    private static readonly TOKENS_TO_WIN;
    private static readonly MAX_DEPTH;
    constructor(core: GameCoreService, random: RandomService, turns: TurnFlowService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleRoll;
    private applyTileEffects;
    private drawAndApplyCard;
    private applyCardEffect;
    private handleMeeting;
    private handleFinish;
    private setWinner;
    private moveAndApply;
    private setPlayerPosition;
    private gainTokens;
    private loseToken;
    private addSkip;
    private setBonusReroll;
    private moveAllPlayers;
    private moveToNextType;
    private moveToPreviousType;
    private transferToken;
    private shareAdvance;
    private rollAndAdvance;
    private rollAndMaybeAdvance;
    private drawCard;
    private replaceMeta;
    private getMeta;
    private getTileByIndex;
    private getPlayerPosition;
    private pickOtherPlayer;
    private pawnLabel;
}
