import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { SetupFlowService } from '../../../../modules/setup-flow/services/setup-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { TurnPoliciesService } from '../../../../modules/turn-policies/services/turn-policies.service';
export declare class ContesActionService {
    private readonly core;
    private readonly random;
    private readonly turns;
    private readonly setupFlow;
    private readonly deckPolicies;
    private readonly turnPolicies?;
    constructor(core: GameCoreService, random: RandomService, turns: TurnFlowService, setupFlow: SetupFlowService, deckPolicies: DeckPoliciesService, turnPolicies?: TurnPoliciesService | undefined);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleChoosePawn;
    private handleRoll;
    private handleRerollDecision;
    private handleChooseTarget;
    private handleChooseNumber;
    private handleChooseOption;
    private handleChooseCard;
    private applyMoveFromRoll;
    private moveBy;
    private applyTileEffect;
    private applyConteTile;
    private drawAndApply;
    private handleDraw;
    private resolveQueuedDraw;
    private continueQueuedDraw;
    private queueDraws;
    private resolveAbondanceDraw;
    private applyBonusEffectById;
    private applyMalusEffectById;
    private applySurpriseEffectById;
    private applyAbondance;
    private applyCoffreMerveilles;
    private drawCard;
    private maybeProtectFromMalus;
    private startChooseTarget;
    private startGiveBonusChoice;
    private listBonusTokens;
    private listSurpriseTokens;
    private startStealTokenChoice;
    private transferBonusToken;
    private transferSurpriseToken;
    private takeOneBonusToken;
    private swapPositions;
    private setTurnSwap;
    private onAnyPlayerPassedBlocked;
    private setWinner;
    private endTurn;
    private applyTurnSwapIfNeeded;
    private swapWithClosestBehind;
    private blockUntilPassed;
    private goToPreviousMalusAndApply;
    private teleport;
    private autoSkipIfBlocked;
    private canUseBonusCards;
    private decrementPerTurn;
    private setPending;
    private setStatusCount;
    private setStatusBool;
    private addStatusCount;
    private pawnLabel;
    private appendTurnAnnouncement;
    private getTurnPolicies;
    private getMeta;
    private getStatusMap;
}
