import game0 from '../games/les-quatre-vents/a-fond-les-ballons/game';
import game1 from '../games/les-quatre-vents/aventure-sauvage/game';
import game2 from '../games/les-quatre-vents/ca-derape/game';
import game3 from '../games/les-quatre-vents/contes-et-cacahuetes/game';
import game4 from '../games/les-quatre-vents/en-attendant-minuit/game';
import game5 from '../games/les-quatre-vents/frousse-party/game';
import game6 from '../games/les-quatre-vents/galopons-ensemble/game';
import game7 from '../games/les-quatre-vents/mission-galaxie/game';
import game8 from '../games/les-quatre-vents/mon-village-mon-histoire/game';
import game9 from '../games/les-quatre-vents/odyssee-quatre-cieux/game';
import game10 from '../games/les-quatre-vents/panier-express/game';
import game11 from '../games/les-quatre-vents/pirates-en-vadrouille/game';
import game12 from '../games/les-quatre-vents/primalis/game';
import game13 from '../games/les-quatre-vents/sac-a-malices/game';
import game14 from '../games/les-quatre-vents/taxi-express/game';
import game15 from '../games/les-quatre-vents/tout-pres-de-maman/game';
import game16 from '../games/les-quatre-vents/voyage-en-terre-de-brumes/game';
import game17 from '../games/vents-dansants/cat-pattes/game';
import game18 from '../games/vents-dansants/cercles-sacres/game';
import game19 from '../games/vents-dansants/dame-nature/game';
import game20 from '../games/vents-dansants/entre-rites-et-lumieres/game';
import game21 from '../games/vents-dansants/gerard-president/game';
import game22 from '../games/vents-dansants/la-bande-a-banane/game';
import game23 from '../games/vents-dansants/la-grande-mine-de-barbak/game';
import game24 from '../games/vents-dansants/la-parade-sucree/game';
import game25 from '../games/vents-dansants/le-marche-des-merveilles/game';
import game26 from '../games/vents-dansants/les-absurdissimes/game';
import game27 from '../games/vents-dansants/les-mains-de-la-terre/game';
import game28 from '../games/vents-dansants/nawak/game';
import game29 from '../games/vents-dansants/olympia/game';
import game30 from '../games/vents-dansants/pimp-my-ride/game';
import game31 from '../games/vents-dansants/zig-et-zag/game';
import game32 from '../games/vents-infinis/arche-de-mnemosyne/game';
import game33 from '../games/vents-sacres/corridor/game';
import game34 from '../games/vents-sacres/foulees-fantastiques/game';
import game35 from '../games/vents-sacres/jeu-oie/game';
import game36 from '../games/vents-sacres/lama/game';
import game37 from '../games/vents-sacres/morpion/game';

/** Generated by commands/generate-game-registry.cjs. Do not edit manually. */
export const GENERATED_GAME_DEFINITIONS: readonly unknown[] = Object.freeze([
  game0,
  game1,
  game2,
  game3,
  game4,
  game5,
  game6,
  game7,
  game8,
  game9,
  game10,
  game11,
  game12,
  game13,
  game14,
  game15,
  game16,
  game17,
  game18,
  game19,
  game20,
  game21,
  game22,
  game23,
  game24,
  game25,
  game26,
  game27,
  game28,
  game29,
  game30,
  game31,
  game32,
  game33,
  game34,
  game35,
  game36,
  game37,
]);
