import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { MinuitSetupService } from './setup/minuit-setup.service';
import { MinuitActionService } from './actions/minuit-action.service';
import { MinuitPresenterService } from './presenter/minuit-presenter.service';
import { MinuitBotService } from './bots/minuit-bot.service';
export declare class EnAttendantMinuitService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "en-attendant-minuit";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "LesQuatreVents";
    readonly displayName: string;
    readonly description = "Course de No\u00EBl jusqu'\u00E0 Minuit.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: MinuitSetupService, actions: MinuitActionService, presenter: MinuitPresenterService, bots: MinuitBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    shouldAnnounceBoardArrivals(): boolean;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
