import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
export declare class LaGrandeMineDeBarbakActionService {
    private readonly core;
    private readonly turns;
    private readonly random;
    private readonly deckPolicies;
    constructor(core: GameCoreService, turns: TurnFlowService, random: RandomService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handlePass;
    private handlePlayCard;
    private ensurePlayerDrawn;
    private playTreasure;
    private playObject;
    private applyEventEffect;
    private applyMonsterEffect;
    private applyCollapseEffect;
    private applyMinorCollapse;
    private applyMajorCollapse;
    private discardRandomFromHand;
    private removeRandomTreasure;
    private removeRandomDomainCard;
    private trimHand;
    private addCardToHand;
    private removeCardFromHand;
    private addCardToDiscard;
    private drawOneCard;
    private finishGame;
    private determineWinner;
    private scoreDomain;
    private clearDrawn;
    private getMeta;
    private setMeta;
    private availableOpponents;
}
