import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { FouleesFantastiquesActionService } from './actions/foulees-fantastiques-action.service';
import { FouleesFantastiquesPhaseService } from './phases/foulees-fantastiques-phase.service';
import { FouleesFantastiquesPresenterService } from './presenter/foulees-fantastiques-presenter.service';
import { FouleesFantastiquesSetupService } from './setup/foulees-fantastiques-setup.service';
import { FouleesFantastiquesBotService } from './bots/foulees-fantastiques-bot.service';
export declare class FouleesFantastiquesService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly phases;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "foulees-fantastiques";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "Les Vents Sacr\u00E9s";
    readonly displayName: string;
    readonly description = "le jeu classique des petits chevaux";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: FouleesFantastiquesSetupService, actions: FouleesFantastiquesActionService, phases: FouleesFantastiquesPhaseService, presenter: FouleesFantastiquesPresenterService, bots: FouleesFantastiquesBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeState(state: GameStateEntity): GameStateWithActions;
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
