import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import { GameCoreService } from '../../../core/services/game-core.service';
import { TurnFlowService } from '../../../modules/turn/services/turn-flow.service';
import { RandomService } from '../../../modules/random/services/random.service';
import { MnemoQuizStoreService } from './store/mnemo-quiz-store.service';
export declare class ArcheDeMnemosyneService extends AbstractGameService {
    private readonly core;
    private readonly turns;
    private readonly store;
    private readonly random;
    readonly gameType = "arche-de-mnemosyne";
    readonly category = "Quiz";
    readonly subcategory = "VentsInfinis";
    readonly displayName = "L'Arche de Mn\u00E9mosyne";
    readonly description = "Quiz \u00E0 cat\u00E9gories (questions al\u00E9atoires).";
    readonly minPlayers = 1;
    readonly maxPlayers = 8;
    constructor(registry: GameRegistryService, core: GameCoreService, turns: TurnFlowService, store: MnemoQuizStoreService, random: RandomService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getShortcuts(ctx: any): import("../../../engine/shortcuts/game-shortcuts").GameShortcutHint[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    private applyOne;
    private resolveQuizIfReady;
    private drawNextQuestionOrStay;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[] | null;
    private parseBool;
    private syncBotPending;
    private buildPendingForUser;
    private buildActionsForUser;
    private back;
    private normalizeStatus;
    private statusLabel;
    private buildConfigPrompt;
    private clampInt;
    private compactQuestionLabel;
    private isOwner;
    private canConfigure;
    private getMeta;
}
