import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { DameNatureActionService } from './actions/dame-nature-action.service';
import { DameNaturePresenterService } from './presenter/dame-nature-presenter.service';
import { DameNatureSetupService } from './setup/dame-nature-setup.service';
import { DameNatureBotService } from './bots/dame-nature-bot.service';
export declare class DameNatureService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "dame-nature";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "VentsDansants";
    readonly displayName: string;
    readonly description = "Collectez quatre familles compl\u00E8tes tout en prot\u00E9geant Dame Nature des pollutions.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: DameNatureSetupService, actions: DameNatureActionService, presenter: DameNaturePresenterService, bots: DameNatureBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
