export const GERARD_PRESIDENT_NAMES = [
  "Annie",
  "Cindy",
  "Rodrigue",
  "Eude",
  "Mireille",
  "Sofiane",
  "Josette",
  "Steve",
  "Chantal",
  "Enzo",
  "Raymonde",
  "Abdoul",
  "Samantha",
  "Jocelyn",
  "Mégane",
  "Norbert",
  "Tiffany",
  "Luigi",
  "Ginette",
  "Brian",
  "Gisèle",
  "Ahmed",
  "Noémie",
  "Michel",
  "Betty",
  "Léon",
  "Tiphaine",
  "Mustapha",
  "Djamila",
  "Fabrice",
  "Nadège",
  "Corentin",
  "Ludivine",
  "Monique",
  "Solange",
  "Cédric",
  "Patricia",
  "Gonzague",
  "Gaëtane",
  "Mamadou",
  "Denise",
  "Maurice",
  "Priscillia",
  "Anatole",
  "Hortense",
  "Marvin",
  "Gertrude",
  "Saïd",
  "Dominique",
  "Paulette",
  "Karim",
  "Bernadette",
  "Lucien",
  "Natacha",
  "Hubert",
  "Béatrice",
  "Séverine",
  "Momo",
  "Blanche",
  "René",
  "Thérèse",
  "Paco",
  "Blaise",
  "Eugène",
  "Pascaline",
  "Zohra",
  "Albert",
  "Léontine",
  "Grégoire",
  "Smaïl",
  "Mirella",
  "Roger",
  "Gladys",
  "Tanguy",
  "Fernand",
  "Amal",
  "Lionel",
  "Suzy",
  "Baptiste",
  "Latifa",
  "Armand",
  "Pierrette",
  "Thierry",
  "Bébert",
  "Claudine",
  "Abdellah",
  "Noël",
  "Denise",
  "Charlotte",
  "Elvis",
  "Karine",
  "Gaston",
  "Roxane",
  "Jacqueline",
  "Hans",
  "Aïcha",
  "Katia",
  "Bertrand",
  "Véro",
  "Alfred",
  "Mirela",
  "Isidore",
  "Soraya",
  "Francis",
  "Samira",
  "Géraldine",
  "Bernard",
  "Laïla",
  "Vincent",
  "Irène",
  "Pierre",
  "Nina",
  "Mehdi",
  "Joséphine",
  "Prosper",
  "Loubna",
  "Claude",
  "Nadine",
  "Philibert",
  "Ã‰liane",
  "Pascal",
  "Zineb",
  "Florent",
  "Mirette",
  "Kamel",
  "Gilberte",
  "Rachid",
  "Clotilde",
  "Diego",
  "Agnès",
  "Sabrina",
  "Constant",
  "Marlène",
  "Roger",
  "Didier",
  "Soso",
  "Frédégonde",
  "Dédé",
  "Océane",
  "Patrick",
  "Edmon",
  "Sylvette",
  "Aboubakar",
  "Céline",
  "Fabien",
  "Malika",
  "Serge",
  "Rose",
  "Justin",
  "Paule",
  "Marcel",
  "Sue",
  "Paul",
  "Sonia",
  "Henri",
  "Maïté",
  "Yannis",
  "Gino",
  "Léonard",
  "Zouina",
  "Roberte",
  "Nicolas",
  "Ghislaine",
  "Loïc",
  "Lydie",
  "Damien",
  "Violette",
  "Samy",
  "Tony",
  "Janine",
  "Béatrice",
  "Jamel",
  "Nicole",
  "Jacques",
  "Maël",
  "Bérengère",
  "Philippe",
  "Adama",
  "Fabienne",
  "Framboise.",
  "Abigaïl",
  "Amandine",
  "Ange",
  "Apollinaire",
  "Archibald",
  "Arielle",
  "Arsène",
  "Assia",
  "Aurore",
  "Axel",
  "Babette",
  "Barbara",
  "Basile",
  "Bella",
  "Benoît",
  "Bianca",
  "Bintou",
  "Brenda",
  "Brigitte",
  "Camilia",
  "Cassandre",
  "Cassius",
  "Cécilia",
  "Charlène",
  "Chloé",
  "Christelle",
  "Chrysostome",
  "Clémentine",
  "Cléopâtre",
  "Colin",
  "Colette",
  "Constance",
  "Constantin",
  "Coraline",
  "Cunégonde",
  "Cyprien",
  "Daphné",
  "Dédéla",
  "Delphine",
  "Dimitri",
  "Djibril",
  "Dolly",
  "Dylan",
  "Ã‰glantine",
  "Ã‰léonore",
  "Ã‰lise",
  "Ã‰lodie",
  "Ã‰mile",
  "Ã‰milie",
  "Ã‰phrem",
  "Ernest",
  "Esméralda",
  "Eugénie",
  "Fanny",
  "Fatou",
  "Faustine",
  "Félicien",
  "Fernande",
  "Flavien",
  "Florence",
  "Frida",
  "Gaël",
  "Geneviève",
  "Georges",
  "Gérard",
  "Ghislain",
  "Giscard",
  "Guillaume",
  "Guy",
  "Huguette",
  "Idriss",
  "Igor",
  "Iman",
  "Ingrid",
  "Irina",
  "Ismaël",
  "Ivan",
  "Izia",
  "Jacky",
  "Jade",
  "Jamila",
  "Jérémie",
  "Jocelyne",
  "José",
  "Josiane",
  "Jules",
  "Juliette",
  "Justine",
  "Kaïs",
  "Katell",
  "Kevin",
  "Kézia",
  "Kheira",
  "Koumba",
  "Léandre",
  "Léa",
  "Léna",
  "Léoncie",
  "Lino",
  "Lison",
  "Louison",
  "Louka,",
  "Lucette",
  "Lucie",
  "Lysandre",
  "Madeleine",
  "Mahé.",
  "Marc",
  "Marie",
  "Nathalie",
  "Sébastien",
  "Sophie",
  "Sylvie",
  "Yolande",
];

export const GERARD_PRESIDENT_THEMES = [
  "Le prénom qui survivrait à une apocalypse de zombies.",
  "Le prénom qui devrait être interdit par décret.",
  "Le prénom le plus flippant dans une cave à 2h du matin.",
  "Le prénom dâ€™un sorcier pas doué mais super motivé.",
  "Le prénom dâ€™un prof de sport ultra-sévère.",
  "Le prénom dâ€™une personne qui mange des cornichons au petit déj.",
  "Le prénom du plus grand séducteur de camping.",
  "Le prénom dâ€™un joueur de pétanque légendaire.",
  "Le prénom dâ€™un dictateur de salon de thé.",
  "Le prénom dâ€™une idole oubliée des années 80.",
  "Le prénom qui défonce tout à Mario Kart.",
  "Le prénom dâ€™un chat psychopathe.",
  "Le prénom dâ€™un maître du karaoké.",
  "Le prénom dâ€™un espion qui se fait toujours griller.",
  "Le prénom dâ€™un animateur de télé parlant trop fort.",
  "Le prénom dâ€™un ninja avec une sciatique.",
  "Le prénom dâ€™un Youtubeur faisant des tutos de pliage de serviettes.",
  "Le prénom dâ€™un pâtissier en reconversion dans le métal.",
  "Le prénom dâ€™un dresseur de pigeons acrobates.",
  "Le prénom dâ€™un gourou de secte vegan astrale.",
  "Le prénom le plus ringard de la galaxie.",
  "Le prénom dâ€™un ancien cascadeur reconverti en banquier.",
  "Le prénom dâ€™un membre dâ€™un boys band improbable.",
  "Le prénom dâ€™une mamie championne dâ€™arts martiaux.",
  "Le prénom dâ€™un vendeur de tapis capable de vendre à un moine.",
  "Le prénom dâ€™un mannequin pour pulls moches.",
  "Le prénom dâ€™un organisateur de mariages catastrophiques.",
  "Le prénom dâ€™un invité relou à tous les anniversaires.",
  "Le prénom dâ€™un prof de yoga fumant en cachette.",
  "Le prénom dâ€™un plombier super-héros du dimanche.",
  "Le prénom dâ€™une star de série télé oubliée.",
  "Le prénom qui a toujours une anecdote gênante.",
  "Le prénom dâ€™un candidat de télé-réalité médiévale.",
  "Le prénom dâ€™un DJ de mariage coincé dans les années disco.",
  "Le prénom dâ€™un personnage de film dâ€™horreur qui meurt en première partie.",
  "Le prénom dâ€™un coach de vie qui pleure devant Top Chef.",
  "Le prénom dâ€™un ado rebelleâ€¦ à lâ€™école de tricot.",
  "Le prénom dâ€™un roi déchu du dancefloor.",
  "Le prénom dâ€™un mec qui vit encore chez sa mère à 52 ans.",
  "Le prénom dâ€™un aventurierâ€¦ qui a peur des pigeons.",
  "Le prénom dâ€™un ou dâ€™une ex quâ€™on ne regrette vraiment pas.",
  "Le prénom dâ€™un joueur dâ€™échecs ultra-suspect.",
  "Le prénom dâ€™un campeur qui parle aux moustiques.",
  "Le prénom dâ€™un joueur de baby-foot invincible.",
  "Le prénom dâ€™un sculpteur de fromages.",
  "Le prénom parfait pour un hamster.",
  "Le prénom dâ€™un influenceur qui fait des unboxings de Tupperware.",
  "Le prénom dâ€™un ange gardienâ€¦ très distrait.",
  "Le prénom dâ€™un livreur de pizza qui arrive toujours froid.",
  "Le prénom dâ€™un pote quâ€™on invite jamais mais qui vient toujours.",
  "Le prénom dâ€™un présentateur météo dépressif.",
  "Le prénom dâ€™un roi de la sieste.",
  "Le prénom dâ€™un mime qui parle tout le temps.",
  "Le prénom dâ€™un chanteur qui rate toutes ses notes.",
  "Le prénom dâ€™un vendeur de lunettes aveugle.",
  "Le prénom dâ€™un barman allergique à lâ€™alcool.",
  "Le prénom dâ€™un éleveur de lamas star de TikTok.",
  "Le prénom dâ€™un chevalier du Moyen Ã‚geâ€¦ mais en claquettes.",
  "Le prénom dâ€™un stagiaire en mission sur la Lune.",
  "Le prénom dâ€™un super-héros super-inutile.",
  "Le prénom dâ€™un poète incomprisâ€¦ parce quâ€™il écrit en morse.",
  "Le prénom dâ€™un cuisinier qui confond sucre et sel.",
  "Le prénom dâ€™un magicien qui perd toujours ses cartes.",
  "Le prénom dâ€™un mec qui se bat contre les ventilateurs.",
  "Le prénom dâ€™un président dâ€™un club de flûte infernal.",
  "Le prénom dâ€™un animateur de bingo sous acide.",
  "Le prénom dâ€™un photographe photophobe.",
  "Le prénom dâ€™un moniteur dâ€™auto-école qui ne sait pas conduire.",
  "Le prénom dâ€™un fan de Star Warsâ€¦ qui croit que Yoda est un Pokémon.",
  "Le prénom dâ€™un concierge de manoir hanté mais optimiste.",
  "Le prénom dâ€™un styliste de bottes ringard.",
  "Le prénom dâ€™un collectionneur de cuillères qui les appelle toutes â€œRogerâ€.",
  "Le prénom dâ€™un médium qui fait peur à son miroir.",
  "Le prénom dâ€™un capitaine de bateau en mousse.",
  "Le prénom dâ€™un sportif de canapé.",
  "Le prénom dâ€™un vendeur dâ€™aspirateurs qui ne le passe jamais.",
  "Le prénom dâ€™un philosophe de fast-food.",
  "Le prénom dâ€™un écolo qui mange des sachets bio.",
  "Le prénom dâ€™un tailleur de barbe pour hérissons.",
  "Le prénom qui inspire la plus grande crainte dans un concours de karaoké",
  "Le prénom dâ€™un animateur de colo qui se fait tirrer les cheveux par les enfants.",
  "Le prénom dâ€™un pilote dâ€™avion qui dort pendant les annonces.",
  "Le prénom dâ€™un mannequinâ€¦ pour charentaises.",
  "Le prénom dâ€™un ado qui fait des tutos maquillage pour serpents.",
  "Le prénom dâ€™un ancien champion de cache-cache jamais retrouvé.",
  "Le prénom dâ€™un bricoleur qui détruit tout sauf son égo.",
  "Le prénom dâ€™un dresseur de plantes carnivores affectueuses.",
  "Le prénom dâ€™un voisin qui espionneâ€¦ avec un drone rose fluo.",
  "Le prénom dâ€™un joueur de Uno banni à vie.",
  "Le prénom dâ€™un chef dâ€™orchestre de klaxons.",
  "Le prénom dâ€™un gourou qui ne croit même pas à sa propre secte.",
  "Le prénom dâ€™un tiktokeur qui fait des danses à la poste.",
  "Le prénom dâ€™un facteur qui confond toujours les boîtes aux lettres.",
  "Le prénom dâ€™un expert en camouflagesâ€¦ en pleine canicule.",
  "Le prénom dâ€™un vendeur de yaourts parlant en alexandrins.",
  "Le prénom dâ€™un gardien de musée volant ses propres objets.",
  "Le prénom dâ€™un imitateur de cloches.",
  "Le prénom dâ€™un pirate des Caraïbesâ€¦ allergique au rhum.",
  "Le prénom dâ€™un médium qui confond les signes astrologiques avec des plats.",
  "Le prénom dâ€™un capitaine de pédalo mégalomane",
];

export interface GerardPresidentSpecialCard {
  id: string;
  name: string;
  description: string;
  effect: string;
}

export const GERARD_PRESIDENT_SPECIAL_CARDS: GerardPresidentSpecialCard[] = [
  {
    id: 'special-sabotage',
    name: "Carte Sabotage",
    description: "Cette carte te permet de désigner un joueur et de lâ€™obliger à justifier à voix haute un prénom qui nâ€™est pas le sien, choisi au hasard parmi ceux posés. Il devra improviser une explication absurde, logique ou hilarante pour ce prénom, même sâ€™il ne lâ€™a pas joué. De quoi créer des situations gênantes ou tordantes, surtout quand le sabotage tombe sur un prénom complètement improbable !",
    effect: 'sabotage',
  },
  {
    id: 'special-double-prenom',
    name: "Carte Double Prénom",
    description: "Grâce à cette carte, tu peux jouer deux prénoms ensemble au lieu dâ€™un seul. Ils doivent former un â€œcomboâ€ crédible, absurde ou ridicule : à toi de créer une association qui fera mouche. Exemple : â€œBébert-Francisâ€ pour un coach de zumba mystique, ou â€œBrigitte-Damoclèsâ€ pour une astrologue de supermarché. Tu joues cette carte au moment où tu poses tes prénoms.",
    effect: 'double-prenom',
  },
  {
    id: 'special-double-theme',
    name: "Carte Double Thème",
    description: "Lorsque tu es le joueur actif et que tu dois lire un thème, tu peux jouer cette carte pour en piocher un deuxième et combiner les deux. Tous les joueurs devront proposer un prénom qui colle aux deux situations en même temps. Cela donne des fusions absurdes comme : â€œLe prénom dâ€™un ancien cascadeur qui donne des cours de flûte à des hyènesâ€ ou â€œLe prénom dâ€™une grand-mère recherchée par Interpolâ€. Fou rire garanti par surcharge dâ€™imagination !",
    effect: 'double-theme',
  },
  {
    id: 'special-interdiction',
    name: "Carte Interdiction",
    description: "Avec cette carte, tu annonces immédiatement après lecture du thème quâ€™un prénom précis est interdit ce tour-ci. Aucun joueur ne pourra poser ce prénom, même sâ€™il est parfait pour le thème. Par exemple, tu peux dire : â€œInterdiction de jouer â€˜Kevinâ€™ !â€ et regarder les autres paniquer sâ€™ils lâ€™avaient en main. Cela perturbe les plans et force à improviser.",
    effect: 'interdiction',
  },
  {
    id: 'special-main-fantome',
    name: "Carte Main Fantôme",
    description: "Tu choisis un joueur, qui devra ce tour-ci jouer un prénom au hasard depuis sa main (sans le regarder !). Il pose la carte face cachée à lâ€™aveugle, et découvre en même temps que tout le monde quel prénom il a envoyé au jury. Parfait pour ajouter un brin de chaos et dâ€™auto-sabotage imprévisible.",
    effect: 'main-fantome',
  },
  {
    id: 'special-defense-totale',
    name: "Carte Défense Totale",
    description: "Cette carte te protège pendant un tour. Si quelquâ€™un tente de te saboter, tâ€™interdire un prénom que tu avais, ou tâ€™imposer une carte Main Fantôme, tu peux dire â€œNon !â€ et annuler lâ€™effet immédiatement. Tu peux aussi lâ€™utiliser pour éviter de devoir justifier ton prénom si tu es désigné. Ã€ jouer juste après quâ€™un effet te cible.",
    effect: 'defense-totale',
  },
  {
    id: 'special-echange-force',
    name: "Carte Ã‰change Forcé",
    description: "Tu désignes un joueur et échangez 1 carte prénom de vos mains, au hasard ou choisie (selon ton choix). Cela peut te sauver dâ€™une main pourrie ou ruiner celle dâ€™un adversaire juste avant un thème parfait.",
    effect: 'echange-force',
  },
  {
    id: 'special-panique-generale',
    name: "Carte Panique Générale",
    description: "Ã€ jouer juste après la lecture dâ€™un thème. Tous les joueurs doivent défausser 3 cartes prénom de leur main et repiocher autant. Ã‡a redistribue les chances et peut déséquilibrer les stratégies. Parfait quand tu sens que dâ€™autres ont de trop bonnes mains !",
    effect: 'panique-generale',
  },
  {
    id: 'special-retour-envoyeur',
    name: "Carte Retour à lâ€™envoyeur",
    description: "Si tu es ciblé par une carte spéciale (Sabotage, Main Fantôme, etc.), tu peux jouer celle-ci pour renvoyer lâ€™effet vers le joueur qui lâ€™a lancé. Petit moment de revanche satisfaisant et de tension imprévisible.",
    effect: 'retour-envoyeur',
  },
  {
    id: 'special-theme-secret',
    name: "Carte Thème Secret",
    description: "Tu es le joueur actif et tu tires le thème en secret. Tu annonces seulement une version raccourcie ou très vague (par exemple â€œLe thème estâ€¦ étrange !â€). Tous les joueurs doivent proposer un prénom à lâ€™aveugle. Puis, tu révèles le thème exact après lecture des prénoms. Cela crée des retournements de situation hilarants et injustesâ€¦ donc forcément très drôles.",
    effect: 'theme-secret',
  },
  {
    id: 'special-chuchotement-confus',
    name: "Carte Chuchotement Confus",
    description: "Tu choisis un joueur qui devra chuchoter son prénom à son voisin de gauche. Le voisin doit ensuite défendre ce prénom à haute voix comme sâ€™il était le sien. Confusion et fous rires garantis !",
    effect: 'chuchotement-confus',
  },
  {
    id: 'special-mega-combo',
    name: "Carte Méga Combo",
    description: "Permet de jouer trois prénoms en un seul, reliés par une histoire complètement improbable. Exemple : â€œGérard, Joséphine et Bob-Le-Cactus, survivants dâ€™une apocalypse de crème chantilly.â€",
    effect: 'mega-combo',
  },
  {
    id: 'special-inversion',
    name: "Carte Inversion",
    description: "Tous les joueurs doivent échanger leur carte prénom jouée avec celle dâ€™un autre joueur de leur choix avant la révélation. Le Maître du Thème voit alors des choix inattendus et absurdes.",
    effect: 'inversion',
  },
  {
    id: 'special-jury-mystere',
    name: "Carte Jury Mystère",
    description: "Pour un tour seulement, le Maître du Thème nâ€™est pas le joueur actif, mais un joueur choisi au hasard parmi ceux qui ont posé un prénom. Il choisit le gagnant à la place. Chaos garanti !",
    effect: 'jury-mystere',
  },
  {
    id: 'special-effet-domino',
    name: "Carte Effet Domino",
    description: "Tu choisis un joueur ciblé : après avoir joué cette carte, chaque joueur suivant doit ajouter un adjectif ridicule à son prénom avant de le poser. Exemple : â€œGérard-Ã‰cureuil-Volant.â€",
    effect: 'effet-domino',
  },
  {
    id: 'special-prenom-fantome',
    name: "Carte Prénom Fantôme",
    description: "Tu joues cette carte après que tous les prénoms soient posés : tu peux ajouter un prénom â€œfantômeâ€ invisible pour le Maître du Thème. Il devra défendre ce prénom en imaginant quâ€™il a été joué par quelquâ€™un.",
    effect: 'prenom-fantome',
  },
  {
    id: 'special-inversion-role',
    name: "Carte Inversion de Rôle",
    description: "Pour ce tour, tous les joueurs deviennent Maîtres du Thème et doivent voter à main levée pour choisir le prénom gagnant. Chaque joueur vote pour celui quâ€™il juge le plus absurde, même si ce nâ€™est pas le sien.",
    effect: 'inversion-role',
  },
  {
    id: 'special-chaos-temporel',
    name: "Carte Chaos Temporel",
    description: "Joue cette carte pour remonter le tour précédent : tous les joueurs reprennent leur prénom posé au tour précédent et le rejouent, mais avec une justification encore plus absurde.",
    effect: 'chaos-temporel',
  },
  {
    id: 'special-ultra-sabotage',
    name: "Carte Ultra Sabotage",
    description: "Similaire à Sabotage, mais cible deux joueurs à la fois, qui doivent chacun justifier un prénom choisi au hasard. Les explications croisées peuvent devenir catastrophiquement drôles.",
    effect: 'ultra-sabotage',
  },
  {
    id: 'special-prenom-volant',
    name: "Carte Prénom Volant",
    description: "Tu choisis un joueur dont tu peux voler une carte prénom de sa main pour la jouer immédiatement, en plus de ton propre prénom. Le joueur volé doit piocher une nouvelle carte en compensation.",
    effect: 'prenom-volant',
  },
];

