export const GERARD_PRESIDENT_NAMES = [
  "Annie",
  "Cindy",
  "Rodrigue",
  "Eude",
  "Mireille",
  "Sofiane",
  "Josette",
  "Steve",
  "Chantal",
  "Enzo",
  "Raymonde",
  "Abdoul",
  "Samantha",
  "Jocelyn",
  "Mégane",
  "Norbert",
  "Tiffany",
  "Luigi",
  "Ginette",
  "Brian",
  "Gisèle",
  "Ahmed",
  "Noémie",
  "Michel",
  "Betty",
  "Léon",
  "Tiphaine",
  "Mustapha",
  "Djamila",
  "Fabrice",
  "Nadège",
  "Corentin",
  "Ludivine",
  "Monique",
  "Solange",
  "Cédric",
  "Patricia",
  "Gonzague",
  "Gaëtane",
  "Mamadou",
  "Denise",
  "Maurice",
  "Priscillia",
  "Anatole",
  "Hortense",
  "Marvin",
  "Gertrude",
  "Saïd",
  "Dominique",
  "Paulette",
  "Karim",
  "Bernadette",
  "Lucien",
  "Natacha",
  "Hubert",
  "Béatrice",
  "Séverine",
  "Momo",
  "Blanche",
  "René",
  "Thérèse",
  "Paco",
  "Blaise",
  "Eugène",
  "Pascaline",
  "Zohra",
  "Albert",
  "Léontine",
  "Grégoire",
  "Smaïl",
  "Mirella",
  "Roger",
  "Gladys",
  "Tanguy",
  "Fernand",
  "Amal",
  "Lionel",
  "Suzy",
  "Baptiste",
  "Latifa",
  "Armand",
  "Pierrette",
  "Thierry",
  "Bébert",
  "Claudine",
  "Abdellah",
  "Noël",
  "Denise",
  "Charlotte",
  "Elvis",
  "Karine",
  "Gaston",
  "Roxane",
  "Jacqueline",
  "Hans",
  "Aïcha",
  "Katia",
  "Bertrand",
  "Véro",
  "Alfred",
  "Mirela",
  "Isidore",
  "Soraya",
  "Francis",
  "Samira",
  "Géraldine",
  "Bernard",
  "Laïla",
  "Vincent",
  "Irène",
  "Pierre",
  "Nina",
  "Mehdi",
  "Joséphine",
  "Prosper",
  "Loubna",
  "Claude",
  "Nadine",
  "Philibert",
  "Éliane",
  "Pascal",
  "Zineb",
  "Florent",
  "Mirette",
  "Kamel",
  "Gilberte",
  "Rachid",
  "Clotilde",
  "Diego",
  "Agnès",
  "Sabrina",
  "Constant",
  "Marlène",
  "Roger",
  "Didier",
  "Soso",
  "Frédégonde",
  "Dédé",
  "Océane",
  "Patrick",
  "Edmon",
  "Sylvette",
  "Aboubakar",
  "Céline",
  "Fabien",
  "Malika",
  "Serge",
  "Rose",
  "Justin",
  "Paule",
  "Marcel",
  "Sue",
  "Paul",
  "Sonia",
  "Henri",
  "Maïté",
  "Yannis",
  "Gino",
  "Léonard",
  "Zouina",
  "Roberte",
  "Nicolas",
  "Ghislaine",
  "Loïc",
  "Lydie",
  "Damien",
  "Violette",
  "Samy",
  "Tony",
  "Janine",
  "Béatrice",
  "Jamel",
  "Nicole",
  "Jacques",
  "Maël",
  "Bérengère",
  "Philippe",
  "Adama",
  "Fabienne",
  "Framboise.",
  "Abigaïl",
  "Amandine",
  "Ange",
  "Apollinaire",
  "Archibald",
  "Arielle",
  "Arsène",
  "Assia",
  "Aurore",
  "Axel",
  "Babette",
  "Barbara",
  "Basile",
  "Bella",
  "Benoît",
  "Bianca",
  "Bintou",
  "Brenda",
  "Brigitte",
  "Camilia",
  "Cassandre",
  "Cassius",
  "Cécilia",
  "Charlène",
  "Chloé",
  "Christelle",
  "Chrysostome",
  "Clémentine",
  "Cléopâtre",
  "Colin",
  "Colette",
  "Constance",
  "Constantin",
  "Coraline",
  "Cunégonde",
  "Cyprien",
  "Daphné",
  "Dédéla",
  "Delphine",
  "Dimitri",
  "Djibril",
  "Dolly",
  "Dylan",
  "Églantine",
  "Éléonore",
  "Élise",
  "Élodie",
  "Émile",
  "Émilie",
  "Éphrem",
  "Ernest",
  "Esméralda",
  "Eugénie",
  "Fanny",
  "Fatou",
  "Faustine",
  "Félicien",
  "Fernande",
  "Flavien",
  "Florence",
  "Frida",
  "Gaël",
  "Geneviève",
  "Georges",
  "Gérard",
  "Ghislain",
  "Giscard",
  "Guillaume",
  "Guy",
  "Huguette",
  "Idriss",
  "Igor",
  "Iman",
  "Ingrid",
  "Irina",
  "Ismaël",
  "Ivan",
  "Izia",
  "Jacky",
  "Jade",
  "Jamila",
  "Jérémie",
  "Jocelyne",
  "José",
  "Josiane",
  "Jules",
  "Juliette",
  "Justine",
  "Kaïs",
  "Katell",
  "Kevin",
  "Kézia",
  "Kheira",
  "Koumba",
  "Léandre",
  "Léa",
  "Léna",
  "Léoncie",
  "Lino",
  "Lison",
  "Louison",
  "Louka,",
  "Lucette",
  "Lucie",
  "Lysandre",
  "Madeleine",
  "Mahé.",
  "Marc",
  "Marie",
  "Nathalie",
  "Sébastien",
  "Sophie",
  "Sylvie",
  "Yolande",
];

export const GERARD_PRESIDENT_THEMES = [
  "Le prénom qui survivrait à une apocalypse de zombies.",
  "Le prénom qui devrait être interdit par décret.",
  "Le prénom le plus flippant dans une cave à 2h du matin.",
  "Le prénom d’un sorcier pas doué mais super motivé.",
  "Le prénom d’un prof de sport ultra-sévère.",
  "Le prénom d’une personne qui mange des cornichons au petit déj.",
  "Le prénom du plus grand séducteur de camping.",
  "Le prénom d’un joueur de pétanque légendaire.",
  "Le prénom d’un dictateur de salon de thé.",
  "Le prénom d’une idole oubliée des années 80.",
  "Le prénom qui défonce tout à Mario Kart.",
  "Le prénom d’un chat psychopathe.",
  "Le prénom d’un maître du karaoké.",
  "Le prénom d’un espion qui se fait toujours griller.",
  "Le prénom d’un animateur de télé parlant trop fort.",
  "Le prénom d’un ninja avec une sciatique.",
  "Le prénom d’un Youtubeur faisant des tutos de pliage de serviettes.",
  "Le prénom d’un pâtissier en reconversion dans le métal.",
  "Le prénom d’un dresseur de pigeons acrobates.",
  "Le prénom d’un gourou de secte vegan astrale.",
  "Le prénom le plus ringard de la galaxie.",
  "Le prénom d’un ancien cascadeur reconverti en banquier.",
  "Le prénom d’un membre d’un boys band improbable.",
  "Le prénom d’une mamie championne d’arts martiaux.",
  "Le prénom d’un vendeur de tapis capable de vendre à un moine.",
  "Le prénom d’un mannequin pour pulls moches.",
  "Le prénom d’un organisateur de mariages catastrophiques.",
  "Le prénom d’un invité relou à tous les anniversaires.",
  "Le prénom d’un prof de yoga fumant en cachette.",
  "Le prénom d’un plombier super-héros du dimanche.",
  "Le prénom d’une star de série télé oubliée.",
  "Le prénom qui a toujours une anecdote gênante.",
  "Le prénom d’un candidat de télé-réalité médiévale.",
  "Le prénom d’un DJ de mariage coincé dans les années disco.",
  "Le prénom d’un personnage de film d’horreur qui meurt en première partie.",
  "Le prénom d’un coach de vie qui pleure devant Top Chef.",
  "Le prénom d’un ado rebelle… à l’école de tricot.",
  "Le prénom d’un roi déchu du dancefloor.",
  "Le prénom d’un mec qui vit encore chez sa mère à 52 ans.",
  "Le prénom d’un aventurier… qui a peur des pigeons.",
  "Le prénom d’un ou d’une ex qu’on ne regrette vraiment pas.",
  "Le prénom d’un joueur d’échecs ultra-suspect.",
  "Le prénom d’un campeur qui parle aux moustiques.",
  "Le prénom d’un joueur de baby-foot invincible.",
  "Le prénom d’un sculpteur de fromages.",
  "Le prénom parfait pour un hamster.",
  "Le prénom d’un influenceur qui fait des unboxings de Tupperware.",
  "Le prénom d’un ange gardien… très distrait.",
  "Le prénom d’un livreur de pizza qui arrive toujours froid.",
  "Le prénom d’un pote qu’on invite jamais mais qui vient toujours.",
  "Le prénom d’un présentateur météo dépressif.",
  "Le prénom d’un roi de la sieste.",
  "Le prénom d’un mime qui parle tout le temps.",
  "Le prénom d’un chanteur qui rate toutes ses notes.",
  "Le prénom d’un vendeur de lunettes aveugle.",
  "Le prénom d’un barman allergique à l’alcool.",
  "Le prénom d’un éleveur de lamas star de TikTok.",
  "Le prénom d’un chevalier du Moyen Âge… mais en claquettes.",
  "Le prénom d’un stagiaire en mission sur la Lune.",
  "Le prénom d’un super-héros super-inutile.",
  "Le prénom d’un poète incompris… parce qu’il écrit en morse.",
  "Le prénom d’un cuisinier qui confond sucre et sel.",
  "Le prénom d’un magicien qui perd toujours ses cartes.",
  "Le prénom d’un mec qui se bat contre les ventilateurs.",
  "Le prénom d’un président d’un club de flûte infernal.",
  "Le prénom d’un animateur de bingo sous acide.",
  "Le prénom d’un photographe photophobe.",
  "Le prénom d’un moniteur d’auto-école qui ne sait pas conduire.",
  "Le prénom d’un fan de Star Wars… qui croit que Yoda est un Pokémon.",
  "Le prénom d’un concierge de manoir hanté mais optimiste.",
  "Le prénom d’un styliste de bottes ringard.",
  "Le prénom d’un collectionneur de cuillères qui les appelle toutes “Roger”.",
  "Le prénom d’un médium qui fait peur à son miroir.",
  "Le prénom d’un capitaine de bateau en mousse.",
  "Le prénom d’un sportif de canapé.",
  "Le prénom d’un vendeur d’aspirateurs qui ne le passe jamais.",
  "Le prénom d’un philosophe de fast-food.",
  "Le prénom d’un écolo qui mange des sachets bio.",
  "Le prénom d’un tailleur de barbe pour hérissons.",
  "Le prénom qui inspire la plus grande crainte dans un concours de karaoké",
  "Le prénom d’un animateur de colo qui se fait tirrer les cheveux par les enfants.",
  "Le prénom d’un pilote d’avion qui dort pendant les annonces.",
  "Le prénom d’un mannequin… pour charentaises.",
  "Le prénom d’un ado qui fait des tutos maquillage pour serpents.",
  "Le prénom d’un ancien champion de cache-cache jamais retrouvé.",
  "Le prénom d’un bricoleur qui détruit tout sauf son égo.",
  "Le prénom d’un dresseur de plantes carnivores affectueuses.",
  "Le prénom d’un voisin qui espionne… avec un drone rose fluo.",
  "Le prénom d’un joueur de Uno banni à vie.",
  "Le prénom d’un chef d’orchestre de klaxons.",
  "Le prénom d’un gourou qui ne croit même pas à sa propre secte.",
  "Le prénom d’un tiktokeur qui fait des danses à la poste.",
  "Le prénom d’un facteur qui confond toujours les boîtes aux lettres.",
  "Le prénom d’un expert en camouflages… en pleine canicule.",
  "Le prénom d’un vendeur de yaourts parlant en alexandrins.",
  "Le prénom d’un gardien de musée volant ses propres objets.",
  "Le prénom d’un imitateur de cloches.",
  "Le prénom d’un pirate des Caraïbes… allergique au rhum.",
  "Le prénom d’un médium qui confond les signes astrologiques avec des plats.",
  "Le prénom d’un capitaine de pédalo mégalomane",
];

export interface GerardPresidentSpecialCard {
  id: string;
  name: string;
  description: string;
  effect: string;
}

export const GERARD_PRESIDENT_SPECIAL_CARDS: GerardPresidentSpecialCard[] = [
  {
    id: 'special-sabotage',
    name: "Carte Sabotage",
    description: "Cette carte te permet de désigner un joueur et de l’obliger à justifier à voix haute un prénom qui n’est pas le sien, choisi au hasard parmi ceux posés. Il devra improviser une explication absurde, logique ou hilarante pour ce prénom, même s’il ne l’a pas joué. De quoi créer des situations gênantes ou tordantes, surtout quand le sabotage tombe sur un prénom complètement improbable !",
    effect: 'sabotage',
  },
  {
    id: 'special-double-prenom',
    name: "Carte Double Prénom",
    description: "Grâce à cette carte, tu peux jouer deux prénoms ensemble au lieu d’un seul. Ils doivent former un “combo” crédible, absurde ou ridicule : à toi de créer une association qui fera mouche. Exemple : “Bébert-Francis” pour un coach de zumba mystique, ou “Brigitte-Damoclès” pour une astrologue de supermarché. Tu joues cette carte au moment où tu poses tes prénoms.",
    effect: 'double-prenom',
  },
  {
    id: 'special-double-theme',
    name: "Carte Double Thème",
    description: "Lorsque tu es le joueur actif et que tu dois lire un thème, tu peux jouer cette carte pour en piocher un deuxième et combiner les deux. Tous les joueurs devront proposer un prénom qui colle aux deux situations en même temps. Cela donne des fusions absurdes comme : “Le prénom d’un ancien cascadeur qui donne des cours de flûte à des hyènes” ou “Le prénom d’une grand-mère recherchée par Interpol”. Fou rire garanti par surcharge d’imagination !",
    effect: 'double-theme',
  },
  {
    id: 'special-interdiction',
    name: "Carte Interdiction",
    description: "Avec cette carte, tu annonces immédiatement après lecture du thème qu’un prénom précis est interdit ce tour-ci. Aucun joueur ne pourra poser ce prénom, même s’il est parfait pour le thème. Par exemple, tu peux dire : “Interdiction de jouer ‘Kevin’ !” et regarder les autres paniquer s’ils l’avaient en main. Cela perturbe les plans et force à improviser.",
    effect: 'interdiction',
  },
  {
    id: 'special-main-fantome',
    name: "Carte Main Fantôme",
    description: "Tu choisis un joueur, qui devra ce tour-ci jouer un prénom au hasard depuis sa main (sans le regarder !). Il pose la carte face cachée à l’aveugle, et découvre en même temps que tout le monde quel prénom il a envoyé au jury. Parfait pour ajouter un brin de chaos et d’auto-sabotage imprévisible.",
    effect: 'main-fantome',
  },
  {
    id: 'special-defense-totale',
    name: "Carte Défense Totale",
    description: "Cette carte te protège pendant un tour. Si quelqu’un tente de te saboter, t’interdire un prénom que tu avais, ou t’imposer une carte Main Fantôme, tu peux dire “Non !” et annuler l’effet immédiatement. Tu peux aussi l’utiliser pour éviter de devoir justifier ton prénom si tu es désigné. À jouer juste après qu’un effet te cible.",
    effect: 'defense-totale',
  },
  {
    id: 'special-echange-force',
    name: "Carte Échange Forcé",
    description: "Tu désignes un joueur et échangez 1 carte prénom de vos mains, au hasard ou choisie (selon ton choix). Cela peut te sauver d’une main pourrie ou ruiner celle d’un adversaire juste avant un thème parfait.",
    effect: 'echange-force',
  },
  {
    id: 'special-panique-generale',
    name: "Carte Panique Générale",
    description: "À jouer juste après la lecture d’un thème. Tous les joueurs doivent défausser 3 cartes prénom de leur main et repiocher autant. Ça redistribue les chances et peut déséquilibrer les stratégies. Parfait quand tu sens que d’autres ont de trop bonnes mains !",
    effect: 'panique-generale',
  },
  {
    id: 'special-retour-envoyeur',
    name: "Carte Retour à l’envoyeur",
    description: "Si tu es ciblé par une carte spéciale (Sabotage, Main Fantôme, etc.), tu peux jouer celle-ci pour renvoyer l’effet vers le joueur qui l’a lancé. Petit moment de revanche satisfaisant et de tension imprévisible.",
    effect: 'retour-envoyeur',
  },
  {
    id: 'special-theme-secret',
    name: "Carte Thème Secret",
    description: "Tu es le joueur actif et tu tires le thème en secret. Tu annonces seulement une version raccourcie ou très vague (par exemple “Le thème est… étrange !”). Tous les joueurs doivent proposer un prénom à l’aveugle. Puis, tu révèles le thème exact après lecture des prénoms. Cela crée des retournements de situation hilarants et injustes… donc forcément très drôles.",
    effect: 'theme-secret',
  },
  {
    id: 'special-chuchotement-confus',
    name: "Carte Chuchotement Confus",
    description: "Tu choisis un joueur qui devra chuchoter son prénom à son voisin de gauche. Le voisin doit ensuite défendre ce prénom à haute voix comme s’il était le sien. Confusion et fous rires garantis !",
    effect: 'chuchotement-confus',
  },
  {
    id: 'special-mega-combo',
    name: "Carte Méga Combo",
    description: "Permet de jouer trois prénoms en un seul, reliés par une histoire complètement improbable. Exemple : “Gérard, Joséphine et Bob-Le-Cactus, survivants d’une apocalypse de crème chantilly.”",
    effect: 'mega-combo',
  },
  {
    id: 'special-inversion',
    name: "Carte Inversion",
    description: "Tous les joueurs doivent échanger leur carte prénom jouée avec celle d’un autre joueur de leur choix avant la révélation. Le Maître du Thème voit alors des choix inattendus et absurdes.",
    effect: 'inversion',
  },
  {
    id: 'special-jury-mystere',
    name: "Carte Jury Mystère",
    description: "Pour un tour seulement, le Maître du Thème n’est pas le joueur actif, mais un joueur choisi au hasard parmi ceux qui ont posé un prénom. Il choisit le gagnant à la place. Chaos garanti !",
    effect: 'jury-mystere',
  },
  {
    id: 'special-effet-domino',
    name: "Carte Effet Domino",
    description: "Tu choisis un joueur ciblé : après avoir joué cette carte, chaque joueur suivant doit ajouter un adjectif ridicule à son prénom avant de le poser. Exemple : “Gérard-Écureuil-Volant.”",
    effect: 'effet-domino',
  },
  {
    id: 'special-prenom-fantome',
    name: "Carte Prénom Fantôme",
    description: "Tu joues cette carte après que tous les prénoms soient posés : tu peux ajouter un prénom “fantôme” invisible pour le Maître du Thème. Il devra défendre ce prénom en imaginant qu’il a été joué par quelqu’un.",
    effect: 'prenom-fantome',
  },
  {
    id: 'special-inversion-role',
    name: "Carte Inversion de Rôle",
    description: "Pour ce tour, tous les joueurs deviennent Maîtres du Thème et doivent voter à main levée pour choisir le prénom gagnant. Chaque joueur vote pour celui qu’il juge le plus absurde, même si ce n’est pas le sien.",
    effect: 'inversion-role',
  },
  {
    id: 'special-chaos-temporel',
    name: "Carte Chaos Temporel",
    description: "Joue cette carte pour remonter le tour précédent : tous les joueurs reprennent leur prénom posé au tour précédent et le rejouent, mais avec une justification encore plus absurde.",
    effect: 'chaos-temporel',
  },
  {
    id: 'special-ultra-sabotage',
    name: "Carte Ultra Sabotage",
    description: "Similaire à Sabotage, mais cible deux joueurs à la fois, qui doivent chacun justifier un prénom choisi au hasard. Les explications croisées peuvent devenir catastrophiquement drôles.",
    effect: 'ultra-sabotage',
  },
  {
    id: 'special-prenom-volant',
    name: "Carte Prénom Volant",
    description: "Tu choisis un joueur dont tu peux voler une carte prénom de sa main pour la jouer immédiatement, en plus de ton propre prénom. Le joueur volé doit piocher une nouvelle carte en compensation.",
    effect: 'prenom-volant',
  },
];
