import type { CardSelectionProgram } from '../contracts/card-selection-program';
import type { GameEffectInstruction } from '../contracts/effect-ir';
import type { JsonStandardVictory } from './json-standard-victory';

export type JsonGameRecipe =
  | 'board-roll'
  | 'board-draw'
  | 'grid-place'
  | 'judged-submit-card'
  | 'judged-pick'
  | 'event-race-roll'
  | 'delivery-race-roll'
  | 'goose-race-roll'
  | 'collection-race-roll'
  | 'ecosystem-race-roll'
  | 'pirate-race-roll'
  | 'parade-play'
  | 'parade-pass'
  | 'nature-families-ask'
  | 'nature-families-pass'
  | 'car-assembly-play'
  | 'car-assembly-discard'
  | 'car-assembly-pass'
  | 'cat-pattes-draw'
  | 'cat-pattes-play'
  | 'cat-pattes-discard'
  | 'wonder-market-buy'
  | 'wonder-market-sell'
  | 'wonder-market-rumor'
  | 'wonder-market-protect'
  | 'wonder-market-steal'
  | 'wonder-market-pass'
  | 'maman-race-roll'
  | 'card-circles-form'
  | 'card-circles-discard'
  | 'card-circles-pass'
  | 'mine-domain-play'
  | 'mine-domain-pass'
  | 'frousse-race-roll'
  | 'galopons-race-roll'
  | 'profession-families-request'
  | 'foulees-race-roll'
  | 'galaxy-race-roll'
  | 'gerard-set-theme'
  | 'gerard-play-name'
  | 'gerard-play-special'
  | 'gerard-choose-winner'
  | 'gerard-pass'
  | 'rites-ask-card'
  | 'rites-pass'
  | 'sac-roll'
  | 'sac-build'
  | 'sac-sell-building'
  | 'sac-mortgage'
  | 'sac-unmortgage'
  | 'sac-pay-fine'
  | 'sac-use-jail-card'
  | 'midnight-race-roll'
  | 'banana-troops-play'
  | 'banana-troops-pass'
  | 'balloon-race-roll'
  | 'balloon-race-draw'
  | 'voyage-roll'
  | 'derape-race-roll'
  | 'nawak-choose'
  | 'nawak-vote'
  | 'olympia-draw'
  | 'olympia-play'
  | 'olympia-pass'
  | 'zig-et-zag-draw'
  | 'mnemosyne-draw'
  | 'mnemosyne-answer'
  | 'mnemosyne-timeout'
  | 'corridor-move'
  | 'corridor-place-wall'
  | 'contes-roll'
  | 'lama-play'
  | 'lama-draw'
  | 'lama-pass'
  | 'lama-quit'
  | 'pawn-race-roll';

export type JsonGameAction = (
  | { effects: readonly GameEffectInstruction[] }
  | { selectCards: CardSelectionProgram }
  | { recipe: JsonGameRecipe }
) & { documentation?: string };

type ProgramVictoryKind =
  | 'by-board'
  | 'by-grid'
  | 'by-judged-cards'
  | 'by-event-race'
  | 'by-delivery-race'
  | 'by-goose-race'
  | 'by-collection-race'
  | 'by-ecosystem-race'
  | 'by-pirate-race'
  | 'by-parade'
  | 'by-nature-families'
  | 'by-car-assembly'
  | 'by-cat-pattes'
  | 'by-wonder-market'
  | 'by-maman-race'
  | 'by-card-circles'
  | 'by-mine-domain'
  | 'by-frousse-race'
  | 'by-galopons-race'
  | 'by-profession-families'
  | 'by-foulees-race'
  | 'by-galaxy-race'
  | 'by-gerard'
  | 'by-rites'
  | 'by-sac'
  | 'by-midnight-race'
  | 'by-banana-troops'
  | 'by-derape-race'
  | 'by-nawak'
  | 'by-olympia'
  | 'by-mnemosyne'
  | 'by-corridor'
  | 'by-contes'
  | 'by-lama'
  | 'by-voyage'
  | 'by-zig-et-zag'
  | 'by-pawn-race';

type ProgramVictory = {
  [Kind in ProgramVictoryKind]: { kind: Kind };
}[ProgramVictoryKind];

export type JsonGameVictory = JsonStandardVictory | ProgramVictory;
