import {
  type AuthorSchema,
  authorId as id,
  authorObject as object,
  authorRecord as record,
  authorArray as array,
  authorBoolean as boolean,
} from '../contracts/json-author-schema';

const position: AuthorSchema = { type: 'integer', minimum: 0 };

export const gooseRacePatternSchema = object(
  {
    kind: { const: 'goose-race' },
    rollRecipe: id,
    trackId: id,
    diceId: id,
    playingPhase: id,
    wellStatus: id,
    finishReason: id,
    maxDepth: { type: 'integer', minimum: 1, maximum: 64 },
    bridgeDestination: position,
    tiles: array(
      object(
        {
          id,
          label: { type: 'string', minLength: 1, maxLength: 2000 },
          description: { type: 'string', maxLength: 10000 },
          type: id,
          turnsToSkip: { type: 'integer', minimum: 1, maximum: 1000 },
          backTo: position,
        },
        ['id', 'label', 'type'],
      ),
      2,
    ),
    pawnSelection: object({ setId: id, choiceId: id }, ['setId', 'choiceId']),
    escapeRolls: array({ type: 'integer', minimum: 1 }, 1),
    forwardRollMaximum: { type: 'integer', minimum: 0 },
    defaultReturn: position,
    defaultSkip: { type: 'integer', minimum: 1 },
    tileRules: record({
      enum: [
        'none',
        'finish',
        'move-to',
        'return',
        'skip',
        'roll-directed',
        'block',
        'repeat-roll',
      ],
    }),
  },
  [
    'kind',
    'rollRecipe',
    'trackId',
    'diceId',
    'playingPhase',
    'wellStatus',
    'finishReason',
    'maxDepth',
    'bridgeDestination',
    'tiles',
    'pawnSelection',
    'escapeRolls',
    'forwardRollMaximum',
    'defaultReturn',
    'defaultSkip',
    'tileRules',
  ],
);

export const cardBattlePatternSchema = object(
  {
    kind: { const: 'card-battle' },
    playRecipe: id,
    deckId: id,
    handId: id,
    totalCards: { type: 'integer', minimum: 1, maximum: 10000 },
    cards: array(
      object(
        {
          id,
          name: { type: 'string', minLength: 1, maxLength: 1000 },
          type: id,
          color: id,
          family: id,
          value: { type: 'number' },
          allowedFamilies: array(id),
        },
        ['id', 'name', 'type', 'color', 'value'],
      ),
      1,
    ),
  },
  ['kind', 'playRecipe', 'deckId', 'handId', 'totalCards', 'cards'],
);

export const trackZoneCollectionPatternSchema = object(
  {
    kind: { const: 'track-zone-collection' },
    rollRecipe: id,
    trackId: id,
    diceId: id,
    finishReason: id,
    eventNamespace: id,
    collectedEvent: id,
    tiles: array(
      object(
        {
          n: { type: 'integer', minimum: 1, maximum: 10000 },
          title: { type: 'string', minLength: 1, maxLength: 2000 },
          description: { type: 'string', maxLength: 10000 },
          type: { enum: ['card', 'finish'] },
        },
        ['n', 'title', 'type'],
      ),
      2,
    ),
    zones: array(
      object(
        {
          id: { type: 'integer', minimum: 1, maximum: 10000 },
          minimumTile: { type: 'integer', minimum: 1, maximum: 10000 },
          maximumTile: { type: 'integer', minimum: 1, maximum: 10000 },
          deckId: id,
          resourceId: id,
        },
        ['id', 'minimumTile', 'maximumTile', 'deckId', 'resourceId'],
      ),
      1,
    ),
  },
  [
    'kind',
    'rollRecipe',
    'trackId',
    'diceId',
    'finishReason',
    'eventNamespace',
    'collectedEvent',
    'tiles',
    'zones',
  ],
);

export const themedSetCollectionPatternSchema = object(
  {
    kind: { const: 'themed-set-collection' },
    formRecipe: id,
    discardRecipe: id,
    passRecipe: id,
    formAction: id,
    discardAction: id,
    passAction: id,
    deckId: id,
    handId: id,
    inventoryId: id,
    cards: array(
      object({
        id,
        name: { type: 'string', minLength: 1, maxLength: 2000 },
        theme: id,
      }),
      1,
    ),
    themes: array(id, 1),
    cardsPerCircle: { type: 'integer', minimum: 1, maximum: 10000 },
    circlesToWin: { type: 'integer', minimum: 1, maximum: 10000 },
    handMinimum: { type: 'integer', minimum: 1, maximum: 10000 },
    handLimit: { type: 'integer', minimum: 1, maximum: 10000 },
    finishReason: id,
    eventNamespace: id,
  },
  [
    'kind',
    'formRecipe',
    'discardRecipe',
    'passRecipe',
    'formAction',
    'discardAction',
    'passAction',
    'deckId',
    'handId',
    'inventoryId',
    'cards',
    'themes',
    'cardsPerCircle',
    'circlesToWin',
    'handMinimum',
    'handLimit',
    'finishReason',
    'eventNamespace',
  ],
);

const text = { type: 'string', minLength: 1, maxLength: 2000 } as const;
export const familyRequestPatternSchema = object(
  {
    kind: { const: 'family-request' },
    askRecipe: id,
    passRecipe: id,
    askAction: id,
    passAction: id,
    deckId: id,
    handId: id,
    setsId: id,
    cards: array(
      {
        oneOf: [
          object({
            id,
            type: { const: 'family' },
            familyId: id,
            familyName: text,
            memberName: text,
          }),
          object({
            id,
            type: { const: 'quiz' },
            question: text,
            choices: array(text, 2),
            answerIndex: { type: 'integer', minimum: 0, maximum: 100 },
          }),
          object({
            id,
            type: { const: 'nature' },
            description: text,
            delta: { type: 'integer', minimum: -1000000, maximum: 1000000 },
          }),
        ],
      },
      1,
    ),
    pollutionCounter: id,
    pollutionLimit: { type: 'integer', minimum: 1 },
    familiesToWin: { type: 'integer', minimum: 1 },
    pollutionFinishReason: id,
    familyFinishReason: id,
    eventNamespace: id,
  },
  [
    'kind',
    'askRecipe',
    'passRecipe',
    'askAction',
    'passAction',
    'deckId',
    'handId',
    'setsId',
    'cards',
    'pollutionCounter',
    'pollutionLimit',
    'familiesToWin',
    'pollutionFinishReason',
    'familyFinishReason',
    'eventNamespace',
  ],
);

const gridSize: AuthorSchema = { type: 'integer', minimum: 1, maximum: 32 };
const gridCoordinate: AuthorSchema = {
  type: 'integer',
  minimum: 0,
  maximum: 31,
};
export const gridPlacementPatternSchema = object(
  {
    kind: { const: 'grid-placement' },
    playRecipe: id,
    playAction: id,
    boardId: id,
    width: gridSize,
    height: gridSize,
    winLength: gridSize,
    drawWhenFull: boolean,
    winnerReason: id,
    drawReason: id,
    markEvent: id,
    preferredCells: array(object({ x: gridCoordinate, y: gridCoordinate })),
    pawnSelection: object(
      {
        setId: id,
        choiceId: id,
        order: { enum: ['players', 'shuffled'] },
        automatic: boolean,
      },
      ['setId', 'choiceId', 'order'],
    ),
  },
  [
    'kind',
    'playRecipe',
    'playAction',
    'boardId',
    'width',
    'height',
    'winLength',
    'drawWhenFull',
    'winnerReason',
    'drawReason',
    'markEvent',
    'preferredCells',
  ],
);

export const orderedAssemblyPatternSchema = object({
  kind: { const: 'ordered-assembly' },
  playRecipe: id,
  discardRecipe: id,
  passRecipe: id,
  playAction: id,
  passAction: id,
  deckId: id,
  handId: id,
  currentInventoryId: id,
  completedInventoryIds: array(id, 1),
  completedNameResources: array(id, 1),
  completedCountResource: id,
  nameCounter: id,
  cards: array(
    object({ id, name: text, category: id }, ['id', 'name', 'category']),
    1,
  ),
  categoryOrder: array(id, 1),
  names: array(
    object({ name: text, description: text }, ['name', 'description']),
    1,
  ),
  setsToWin: { type: 'integer', minimum: 1 },
  finishReason: id,
  eventNamespace: id,
});

export const judgedSubmissionPatternSchema = object({
  kind: { const: 'judged-submission' },
  submitRecipe: id,
  pickRecipe: id,
  submitAction: id,
  pickAction: id,
  judgeId: id,
  submissionId: id,
  promptDeckId: id,
  answerDeckId: id,
  answerHandId: id,
  collectingPhase: id,
  judgingPhase: id,
  scoreToWin: { type: 'integer', minimum: 1 },
  winningReason: id,
  submittedMessage: id,
  revealedEvent: id,
  botSelection: { enum: ['first', 'random'] },
});

export const anonymousVotePatternSchema = object({
  kind: { const: 'anonymous-vote' },
  chooseRecipe: id,
  voteRecipe: id,
  chooseAction: id,
  voteAction: id,
  answerSubmissionId: id,
  voteSubmissionId: id,
  targetScore: { type: 'integer', minimum: 1, maximum: 1000 },
  winnerReason: id,
  challenges: array(
    object(
      {
        id,
        prompt: { type: 'string', minLength: 1, maxLength: 10000 },
        answers: { ...array(text, 2), maxItems: 100 },
      },
      ['id', 'prompt', 'answers'],
    ),
    1,
  ),
  eventNamespace: id,
});

export const marketPatternSchema = object(
  {
    kind: { const: 'market' },
    marketId: id,
    inventoryId: id,
    items: array(id, 1),
    currency: id,
    prices: record({ type: 'integer', minimum: 0, maximum: 1000000 }),
    startingCurrency: { type: 'integer', minimum: 0, maximum: 1000000 },
    minPrice: { type: 'integer', minimum: 0, maximum: 1000000 },
    maxPrice: { type: 'integer', minimum: 0, maximum: 1000000 },
    turnsCounterId: id,
    maxRounds: { type: 'integer', minimum: 1, maximum: 10000 },
    winnerReason: id,
    exchange: object({
      buyRecipe: id,
      sellRecipe: id,
      rumorRecipe: id,
      protectRecipe: id,
      stealRecipe: id,
      passRecipe: id,
      buyAction: id,
      sellAction: id,
      passAction: id,
      rumorCost: { type: 'integer', minimum: 0, maximum: 1000000 },
      protectCost: { type: 'integer', minimum: 0, maximum: 1000000 },
      eventNamespace: id,
    }),
  },
  [
    'kind',
    'marketId',
    'inventoryId',
    'items',
    'currency',
    'prices',
    'startingCurrency',
    'minPrice',
    'maxPrice',
    'turnsCounterId',
    'maxRounds',
    'winnerReason',
  ],
);
