import type { CardSelectionProgram } from '../effect-packs/choice-card-occurrences/program';
import type { GameEffectInstruction } from '../contracts/effect-ir';
import type { JsonStandardVictory } from './json-standard-victory';

export type JsonGameRecipe =
  | 'board-roll'
  | 'board-draw'
  | 'grid-place'
  | 'judged-submit-card'
  | 'judged-pick'
  | 'race-event-cards-roll'
  | 'race-route-delivery-roll'
  | 'race-goose-track-roll'
  | 'collection-track-zones-roll'
  | 'race-resource-track-roll'
  | 'race-treasure-track-roll'
  | 'cards-ordered-parade-play'
  | 'cards-ordered-parade-pass'
  | 'collection-family-request-ask'
  | 'collection-family-request-pass'
  | 'cards-ordered-assembly-play'
  | 'cards-ordered-assembly-discard'
  | 'cards-ordered-assembly-pass'
  | 'paw-round-draw'
  | 'paw-round-play'
  | 'paw-round-discard'
  | 'collection-market-exchange-buy'
  | 'collection-market-exchange-sell'
  | 'collection-market-exchange-rumor'
  | 'collection-market-exchange-protect'
  | 'collection-market-exchange-steal'
  | 'collection-market-exchange-pass'
  | 'race-paired-pawns-roll'
  | 'collection-themed-circles-form'
  | 'collection-themed-circles-discard'
  | 'collection-themed-circles-pass'
  | 'cards-public-domain-play'
  | 'cards-public-domain-pass'
  | 'race-protected-haunted-track-roll'
  | 'race-bidirectional-collision-roll'
  | 'collection-family-effects-request'
  | 'race-team-pawn-capture-roll'
  | 'race-quiz-event-track-roll'
  | 'cards-theme-name-set-theme'
  | 'cards-theme-name-play-name'
  | 'cards-theme-name-play-special'
  | 'cards-theme-name-choose-winner'
  | 'cards-theme-name-pass'
  | 'cards-ritual-phases-ask-card'
  | 'cards-ritual-phases-pass'
  | 'board-property-economy-roll'
  | 'board-property-economy-build'
  | 'board-property-economy-sell-building'
  | 'board-property-economy-mortgage'
  | 'board-property-economy-unmortgage'
  | 'board-property-economy-pay-fine'
  | 'board-property-economy-use-jail-card'
  | 'race-bounce-quiz-roll'
  | 'collection-species-troops-play'
  | 'collection-species-troops-pass'
  | 'race-chained-tile-cards-roll'
  | 'race-chained-tile-cards-draw'
  | 'choice-chapter-encounter-roll'
  | 'race-hazard-roll'
  | 'choice-anonymous-vote-choose'
  | 'choice-anonymous-vote-vote'
  | 'cards-shared-prestige-draw'
  | 'cards-shared-prestige-play'
  | 'cards-shared-prestige-pass'
  | 'cards-battle-ties-draw'
  | 'choice-simultaneous-quiz-draw'
  | 'choice-simultaneous-quiz-answer'
  | 'choice-simultaneous-quiz-timeout'
  | 'board-path-walls-move'
  | 'board-path-walls-place-wall'
  | 'choice-story-challenge-roll'
  | 'cards-discard-penalty-play'
  | 'cards-discard-penalty-draw'
  | 'cards-discard-penalty-pass'
  | 'cards-discard-penalty-quit'
  | 'race-multi-pawn-roll';

export type JsonGameAction = (
  | { effects: readonly GameEffectInstruction[] }
  | { selectCards: CardSelectionProgram }
  | { recipe: JsonGameRecipe }
) & { documentation?: string };

type ProgramVictoryKind =
  | 'by-board'
  | 'by-grid'
  | 'by-judged-cards'
  | 'by-event-race'
  | 'by-delivery-race'
  | 'by-goose-race'
  | 'by-track-zone-collection'
  | 'by-resource-track-race'
  | 'by-treasure-track-race'
  | 'by-parade'
  | 'by-family-request'
  | 'by-car-assembly'
  | 'by-paw-scoring'
  | 'by-market-exchange'
  | 'by-paired-pawn-race'
  | 'by-card-circles'
  | 'by-public-domain-cards'
  | 'by-protected-haunted-race'
  | 'by-bidirectional-collision-race'
  | 'by-family-effects'
  | 'by-team-pawn-race'
  | 'by-quiz-event-race'
  | 'by-theme-name-cards'
  | 'by-ritual-phases'
  | 'by-property-economy'
  | 'by-bounce-quiz-race'
  | 'by-species-troops'
  | 'by-directional-hazard-race'
  | 'by-anonymous-vote'
  | 'by-shared-prestige-cards'
  | 'by-simultaneous-quiz'
  | 'by-path-walls'
  | 'by-story-challenge'
  | 'by-discard-penalty-cards'
  | 'by-chapter-encounter'
  | 'by-battle-ties'
  | 'by-pawn-race';

type ProgramVictory = {
  [Kind in ProgramVictoryKind]: { kind: Kind };
}[ProgramVictoryKind];

export type JsonGameVictory = JsonStandardVictory | ProgramVictory;
