import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
export declare class BandeABananeActionService {
    private readonly core;
    private readonly turns;
    private readonly random;
    private readonly deckPolicies;
    private static readonly HAND_LIMIT;
    constructor(core: GameCoreService, turns: TurnFlowService, random: RandomService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handlePass;
    private handlePlayCard;
    private playMonkey;
    private playJoker;
    private playAction;
    private playTrap;
    private playVol;
    private playCris;
    private playGrimpeur;
    private addCardToTroop;
    private enforceHandLimit;
    private addSkipTurns;
    private discardRandomCard;
    private drawForPlayer;
    private drawOneCard;
    private ensurePlayerDrawn;
    private clearDrawn;
    private getMeta;
    private setMeta;
    private playerHasCard;
    private getPlayerHand;
    private addCardToHand;
    private removeCardFromHand;
    private addCardToDiscard;
    private getCardName;
    private hasWinningTroupe;
}
