import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { MissionGalaxieSetupService } from './setup/mission-galaxie-setup.service';
import { MissionGalaxieActionService } from './actions/mission-galaxie-action.service';
import { MissionGalaxiePresenterService } from './presenter/mission-galaxie-presenter.service';
import { MissionGalaxieBotService } from './bots/mission-galaxie-bot.service';
export declare class MissionGalaxieService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "mission-galaxie";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "LesQuatreVents";
    readonly displayName: string;
    readonly description = "Course cosmique autour de 50 cases : questions, d\u00E9fis et \u00E9v\u00E9nements vous propulsent vers la plan\u00E8te l\u00E9gendaire.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: MissionGalaxieSetupService, actions: MissionGalaxieActionService, presenter: MissionGalaxiePresenterService, bots: MissionGalaxieBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
