import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { VoyageSetupService } from './setup/voyage-setup.service';
import { VoyageActionService } from './actions/voyage-action.service';
import { VoyagePresenterService } from './presenter/voyage-presenter.service';
import { VoyageBotService } from './bots/voyage-bot.service';
export declare class VoyageService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "voyage-en-terre-de-brumes";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "LesQuatreVents";
    readonly displayName: string;
    readonly description = "Voyage en Irlande : quiz de l\u00E9gendes, farces et tr\u00E9sors.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: VoyageSetupService, actions: VoyageActionService, presenter: VoyagePresenterService, bots: VoyageBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
