export type LamaCardValue = 1 | 2 | 3 | 4 | 5 | 6 | 7;
export type LamaRoundStep = 'setup_config' | 'turn_choice' | 'return_token' | 'round_pause';
export type LamaMetadata = {
    rng?: Record<string, any>;
    ownerPlayerId: number | null;
    loseAtScore: number | null;
    roundPauseSeconds: number | null;
    allowPlayAfterDraw: boolean;
    roundPauseUntilMs: number | null;
    roundNumber: number;
    roundStarterIndex: number;
    endedRoundNumber?: number | null;
    deck: LamaCardValue[];
    discard: LamaCardValue[];
    handsByPlayerId: Record<string, LamaCardValue[]>;
    droppedOutByPlayerId: Record<string, boolean>;
    scoresByPlayerId: Record<string, number>;
    eliminatedByPlayerId?: Record<string, boolean>;
    step: LamaRoundStep;
    turnTracker?: {
        playerId: number | null;
        drawn: boolean;
        played: boolean;
    };
    lastDrawTurnIndexByPlayerId?: Record<string, number>;
    pendingReturnQueue: number[];
    pendingReturnPlayerId: number | null;
    winnerId?: number | null;
    suppressTurnAnnouncement?: boolean;
};
export declare const LAMA_VALUE: LamaCardValue;
export declare const lamaCardLabel: (v: LamaCardValue) => string;
export declare const lamaCardScore: (v: LamaCardValue) => number;
export declare const nextLamaValue: (top: LamaCardValue) => LamaCardValue;
