INSERT INTO `bot_names` (`name`, `enabled`)
VALUES
  ('BibiBarrique', 1),
  ('GrogMatic', 1),
  ('Tavernicus', 1),
  ('Bidouillard', 1),
  ('MousseMecanique', 1),
  ('BourraBot', 1),
  ('TonneauTron', 1),
  ('Farfouillex', 1),
  ('GagaGolem', 1),
  ('MarmiteRoulante', 1),
  ('CouscousKran', 1),
  ('GnoleGear', 1),
  ('Picolotron', 1),
  ('FutFou', 1),
  ('Ivre-Tonique', 1),
  ('Barbotine', 1),
  ('ChopineX', 1),
  ('Gargouillix', 1),
  ('TroubadourBot', 1),
  ('Fiascobot', 1),
  ('Brasse-Bouze', 1),
  ('Caskouille', 1),
  ('Fripouille5000', 1),
  ('CervoMousse', 1),
  ('BazarBorg', 1),
  ('Poivrotix', 1),
  ('CraquelinBot', 1),
  ('Loqueteux', 1),
  ('Grelottin', 1),
  ('Soupe-a-Bot', 1)
ON DUPLICATE KEY UPDATE enabled = VALUES(enabled);
