network.http.base=http://127.0.0.1:8000/api/
network.ws.url=ws://127.0.0.1:8081/ws
network.ws.presence=ws://127.0.0.1:8081/presence
app.version=1.0.8
updates.check.url=http://127.0.0.1:8000/client/version
updates.root.dir=.
updates.auth.token=7e0b7da0b61a4c2cb4c6373dd5d5952c
