/** Reviewed extension API; internal runtime paths are not part of the pack interface. */
export { assertUniqueAuthorIds } from '../runtime/contracts/authoring-diagnostics';
export { assertUniqueAuthorValues } from '../runtime/contracts/authoring-diagnostics';
export { authorArray } from '../runtime/contracts/json-author-schema';
export { authorBoolean } from '../runtime/contracts/json-author-schema';
export { authorId } from '../runtime/contracts/json-author-schema';
export { AuthoringError } from '../runtime/contracts/authoring-error';
export { authoringFailure } from '../runtime/contracts/authoring-diagnostics';
export type { AuthoringFailure } from '../runtime/contracts/authoring-diagnostics';
export { authoringProperty } from '../runtime/contracts/authoring-diagnostics';
export { authoringValueAt } from '../runtime/contracts/authoring-error';
export { authorInteger } from '../runtime/contracts/json-author-schema';
export { authorNumber } from '../runtime/contracts/json-author-schema';
export { authorObject } from '../runtime/contracts/json-author-schema';
export { authorPositive } from '../runtime/contracts/json-author-schema';
export { authorRecord } from '../runtime/contracts/json-author-schema';
export { authorRef } from '../runtime/contracts/json-author-schema';
export type { AuthorSchema } from '../runtime/contracts/json-author-schema';
export type { BoardGameProgram } from '../runtime/contracts/board-landing-contract';
export type { BoardLanding } from '../runtime/contracts/board-landing-contract';
export type { ChoiceResolverShape } from '../runtime/contracts/author-rule-contracts';
export { clockwise } from '../runtime/kits/turn-kit';
export { createJsonGameCompiler } from '../runtime/definitions/json-game-compiler-factory';
export { defineAction } from '../runtime/actions/action-builders';
export { defineActorEffect } from '../runtime/effects/effects-core';
export { defineChoice } from '../runtime/actions/action-builders';
export { defineEffect } from '../runtime/effects/effects-core';
export { defineEmptyAction } from '../runtime/actions/action-builders';
export { defineEmptyEffect } from '../runtime/effects/effects-core';
export { defineJsonEffectPack } from '../runtime/contracts/json-effect-pack';
export { effectJsonSchema } from '../runtime/contracts/effect-json-schema';
export type { GameComponentDefinition } from '../runtime/definitions/component-kit';
export type { GameEffectResolverShape } from '../runtime/contracts/effect-resolver';
export type { GamePhaseSet } from '../runtime/kits/phase-kit';
export { GameRuleViolationError } from '../runtime/contracts/game-domain.errors';
export { GameStateViolationError } from '../runtime/contracts/game-domain.errors';
export type { GridPosition } from '../runtime/kits/grid-kit';
export { isEngineEventType } from '../runtime/events/engine-event-registry';
export { isRecord } from '../runtime/content/content-guards';
export type { JsonContentAssets } from '../runtime/content/json-content-bundle';
export type { JsonEffectPackDomain } from '../runtime/contracts/json-effect-pack';
export type { JsonEffectPackCapability } from '../runtime/contracts/json-effect-pack';
export type { JsonEffectPackViews } from '../runtime/contracts/json-effect-pack-catalog';
export type { JsonGameCoreDocument } from '../runtime/definitions/json-game-core-document';
export type { JsonGameManifest } from '../runtime/definitions/json-game-manifest';
export type { JsonGameViewAugmentation } from '../runtime/contracts/json-effect-pack-catalog';
export { rejectRule } from '../runtime/contracts/game-domain.errors';
export { resolveJsonContent } from '../runtime/content/json-content-bundle';
export { scanGridWinner } from '../runtime/kits/grid-kit';
