export type GerardPresidentRoundPhase = 'waiting_theme' | 'collecting_names' | 'choosing_winner';
export interface GerardPresidentMetadata {
    rng?: Record<string, unknown>;
    nameDeck: string[];
    themeDeck: string[];
    specialDeck: string[];
    nameDiscard: string[];
    themeDiscard: string[];
    specialDiscard: string[];
    hands: Record<number, string[]>;
    specialHands: Record<number, string[]>;
    scores: Record<number, number>;
    masterId?: number | null;
    currentTheme?: string | null;
    secondTheme?: string | null;
    lockedName?: string | null;
    peaceTurnsRemaining?: number;
    winnerId?: number | null;
    roundNumber: number;
    targetScore: number;
    submissions: Record<number, string[]>;
    pendingPlayers: number[];
    roundPhase: GerardPresidentRoundPhase;
    specialsPlayed: Record<number, string[]>;
    extraNamesAllowed: Record<number, number>;
    defenseActive: Record<number, boolean>;
    specialAttackers: Record<number, number[]>;
    themeSecretActive?: boolean;
    juryOverrideId?: number | null;
    dominoRemaining?: number;
    ghostNames: string[];
}
export declare const GERARD_PRESIDENT_TARGET_SCORE = 7;
