import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { TurnFlowService } from '../../../../modules/turn/services/turn-flow.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
export declare class PiratesEnVadrouilleActionService {
    private readonly random;
    private readonly turns;
    private readonly core;
    private readonly deckPolicies;
    constructor(random: RandomService, turns: TurnFlowService, core: GameCoreService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private handleRoll;
    private handleChooseTarget;
    private applyLanding;
    private drawCard;
    private applyBonusCard;
    private applyObstacleCard;
    private applyTargetEffect;
    private promptTargetSelection;
    private collectGold;
    private handleFinish;
    private addCardToCollection;
    private setCollection;
    private addSkip;
    private addImmunity;
    private modifyGold;
    private setKeepTurn;
    private drawFromDeck;
    private formatActionMessage;
    private getCollection;
    private getTotalCards;
    private move;
    private setPos;
    private pawnLabel;
    private getMeta;
}
