app.name=Le Monde de Lila
network.http.base=http://127.0.0.1:3001/api/
network.ws.url=ws://127.0.0.1:3001/ws
network.ws.api=ws://127.0.0.1:3001/ws/api
network.ws.game=ws://127.0.0.1:3001/ws/game
network.ws.notify=ws://127.0.0.1:3001/ws/notify
network.ws.secret=remote-ws-shared-secret-2025
