import { OnGatewayConnection, OnGatewayDisconnect } from '@nestjs/websockets';
import { Server } from 'ws';
import { GameEngineService } from '../services/game-engine.service';
import { WsJwtAuthService } from '../../../common/ws/ws-jwt-auth.service';
import { PerfMetricsService } from '../../../common/services/perf-metrics.service';
import { ClientUpdatesService } from '../../../client-updates/services/client-updates.service';
import { WsTicketAuthService } from '../../../common/ws/ws-ticket-auth.service';
import { RoomService } from '../../../room/services/room.service';
import { GameContentService } from '../services/game-content.service';
import type { WsClientLike } from '../../../common/ws/ws-jwt-auth.service';
interface GameWebSocket extends WsClientLike {
    readyState: number;
    send(data: string, cb?: (err?: Error) => void): void;
    close(code?: number, reason?: string): void;
    terminate(): void;
    ping(): void;
    on(event: string, listener: (...args: unknown[]) => void): void;
}
export declare class GameGateway implements OnGatewayConnection<GameWebSocket>, OnGatewayDisconnect<GameWebSocket> {
    private readonly engine;
    private readonly auth;
    private readonly perf;
    private readonly clientUpdates;
    private readonly wsTickets;
    private readonly roomService;
    private readonly content;
    server: Server<GameWebSocket>;
    private readonly clients;
    private readonly rooms;
    private readonly heartbeats;
    private readonly lastPong;
    private readonly encodedStateMessageCache;
    private readonly topLevelSnapshotCache;
    private readonly lastPayloadBySocket;
    private readonly pingIntervalMs;
    private readonly pongGraceMs;
    private readonly minPatchBytesSaved;
    private readonly logger;
    constructor(engine: GameEngineService, auth: WsJwtAuthService, perf: PerfMetricsService, clientUpdates: ClientUpdatesService, wsTickets: WsTicketAuthService, roomService: RoomService, content: GameContentService);
    handleConnection(client: GameWebSocket, ...args: unknown[]): Promise<void>;
    handleDisconnect(client: GameWebSocket): void;
    private handleMessage;
    private handleJoin;
    private handleRules;
    private handleState;
    private handleTurn;
    private handleActions;
    private handleKey;
    private handleBot;
    private broadcastState;
    private broadcastEnded;
    private setRoom;
    private forceDisconnectRoomClients;
    private sendError;
    private unsafeStringify;
    private sanitizeOutgoingPayload;
    private safeSend;
    private sendState;
    private getEncodedStateMessage;
    private buildEncodedPatch;
    private buildTopLevelPatch;
    private getTopLevelSnapshot;
    private decode;
    private resolveAuth;
    private tryAutoJoinFromUrl;
    private ensureRoomContext;
    private extractJoinParams;
    private extractTrace;
    private computeClientLatency;
    private parseNumberFromPayload;
    private parseStringFromPayload;
    private extractIncomingActions;
    private isGameSingleActionDto;
    private resolveUrlCandidate;
    private buildRoomKey;
}
export {};
