// Generated by commands/generate-effect-pack-registry.cjs. Do not edit.
import type { JsonEffectPackDomain } from '../../engine/sdk/extension-api';
import { effectPack as raceResourceTrackEffectPack } from '../game-specific/race-resource-track/effect-pack';
import { effectPack as cardsPublicDomainEffectPack } from '../game-specific/cards-public-domain/effect-pack';
import { effectPack as raceProtectedHauntedTrackEffectPack } from '../game-specific/race-protected-haunted-track/effect-pack';
import { effectPack as raceTeamPawnCaptureEffectPack } from '../game-specific/race-team-pawn-capture/effect-pack';
import { effectPack as raceQuizEventTrackEffectPack } from '../game-specific/race-quiz-event-track/effect-pack';
import { effectPack as raceDirectionalHazardsEffectPack } from '../game-specific/race-directional-hazards/effect-pack';
import { effectPack as raceChainedTileCardsEffectPack } from '../game-specific/race-chained-tile-cards/effect-pack';
import { effectPack as choiceChapterEncounterEffectPack } from '../game-specific/choice-chapter-encounter/effect-pack';
import { effectPack as choiceSimultaneousPawScoringEffectPack } from '../game-specific/choice-simultaneous-paw-scoring/effect-pack';
import { effectPack as cardsThemeNameEffectPack } from '../game-specific/cards-theme-name/effect-pack';
import { effectPack as cardsRitualPhasesEffectPack } from '../game-specific/cards-ritual-phases/effect-pack';
import { effectPack as boardPropertyEconomyEffectPack } from '../game-specific/board-property-economy/effect-pack';
import { effectPack as cardsSharedPrestigeEffectPack } from '../game-specific/cards-shared-prestige/effect-pack';
import { effectPack as choiceSimultaneousQuizEffectPack } from '../game-specific/choice-simultaneous-quiz/effect-pack';
import { effectPack as boardPathWallsEffectPack } from '../game-specific/board-path-walls/effect-pack';
import { effectPack as choiceStoryChallengeEffectPack } from '../game-specific/choice-story-challenge/effect-pack';
import { effectPack as cardsDiscardPenaltyEffectPack } from '../game-specific/cards-discard-penalty/effect-pack';
import { effectPack as boardMovementLandingsEffectPack } from '../game-specific/board-movement-landings/effect-pack';

/** Deterministic composition root. No filesystem discovery occurs at runtime. */
export const jsonEffectPacks = Object.freeze([
  raceResourceTrackEffectPack,
  cardsPublicDomainEffectPack,
  raceProtectedHauntedTrackEffectPack,
  raceTeamPawnCaptureEffectPack,
  raceQuizEventTrackEffectPack,
  raceDirectionalHazardsEffectPack,
  raceChainedTileCardsEffectPack,
  choiceChapterEncounterEffectPack,
  choiceSimultaneousPawScoringEffectPack,
  cardsThemeNameEffectPack,
  cardsRitualPhasesEffectPack,
  boardPropertyEconomyEffectPack,
  cardsSharedPrestigeEffectPack,
  choiceSimultaneousQuizEffectPack,
  boardPathWallsEffectPack,
  choiceStoryChallengeEffectPack,
  cardsDiscardPenaltyEffectPack,
  boardMovementLandingsEffectPack,
] as const);

export type RegisteredJsonEffectPack = (typeof jsonEffectPacks)[number];
type EffectPacksByDomain = Readonly<
  Partial<Record<JsonEffectPackDomain, readonly RegisteredJsonEffectPack[]>>
>;
export const jsonEffectPacksByDomain: EffectPacksByDomain = (() => {
  const domains = new Map<JsonEffectPackDomain, RegisteredJsonEffectPack[]>();
  for (const pack of jsonEffectPacks) {
    const members = domains.get(pack.domain) ?? [];
    members.push(pack);
    domains.set(pack.domain, members);
  }
  return Object.freeze(
    Object.fromEntries(
      [...domains].map(([domain, packs]) => [domain, Object.freeze(packs)]),
    ),
  );
})();
