// Generated by commands/generate-effect-pack-registry.cjs. Do not edit.
import type { JsonEffectPackDomain } from '../../engine/runtime/contracts/json-effect-pack';
import { effectPack as raceMultiPawnEffectPack } from '../game-specific/race-multi-pawn/effect-pack';
import { effectPack as raceEventCardsEffectPack } from '../game-specific/race-event-cards/effect-pack';
import { effectPack as raceRouteDeliveryEffectPack } from '../game-specific/race-route-delivery/effect-pack';
import { effectPack as raceGooseTrackEffectPack } from '../game-specific/race-goose-track/effect-pack';
import { effectPack as collectionTrackZonesEffectPack } from '../game-specific/collection-track-zones/effect-pack';
import { effectPack as raceResourceTrackEffectPack } from '../game-specific/race-resource-track/effect-pack';
import { effectPack as raceTreasureTrackEffectPack } from '../game-specific/race-treasure-track/effect-pack';
import { effectPack as cardsOrderedParadeEffectPack } from '../game-specific/cards-ordered-parade/effect-pack';
import { effectPack as collectionFamilyRequestEffectPack } from '../game-specific/collection-family-request/effect-pack';
import { effectPack as cardsOrderedAssemblyEffectPack } from '../game-specific/cards-ordered-assembly/effect-pack';
import { effectPack as collectionMarketExchangeEffectPack } from '../game-specific/collection-market-exchange/effect-pack';
import { effectPack as racePairedPawnsEffectPack } from '../game-specific/race-paired-pawns/effect-pack';
import { effectPack as collectionThemedCirclesEffectPack } from '../game-specific/collection-themed-circles/effect-pack';
import { effectPack as cardsPublicDomainEffectPack } from '../game-specific/cards-public-domain/effect-pack';
import { effectPack as raceProtectedHauntedTrackEffectPack } from '../game-specific/race-protected-haunted-track/effect-pack';
import { effectPack as raceBidirectionalCollisionEffectPack } from '../game-specific/race-bidirectional-collision/effect-pack';
import { effectPack as collectionFamilyEffectsEffectPack } from '../game-specific/collection-family-effects/effect-pack';
import { effectPack as raceTeamPawnCaptureEffectPack } from '../game-specific/race-team-pawn-capture/effect-pack';
import { effectPack as raceQuizEventTrackEffectPack } from '../game-specific/race-quiz-event-track/effect-pack';
import { effectPack as raceBounceQuizEffectPack } from '../game-specific/race-bounce-quiz/effect-pack';
import { effectPack as collectionSpeciesTroopsEffectPack } from '../game-specific/collection-species-troops/effect-pack';
import { effectPack as raceDirectionalHazardsEffectPack } from '../game-specific/race-directional-hazards/effect-pack';
import { effectPack as raceChainedTileCardsEffectPack } from '../game-specific/race-chained-tile-cards/effect-pack';
import { effectPack as choiceChapterEncounterEffectPack } from '../game-specific/choice-chapter-encounter/effect-pack';
import { effectPack as choiceSimultaneousPawScoringEffectPack } from '../game-specific/choice-simultaneous-paw-scoring/effect-pack';
import { effectPack as cardsThemeNameEffectPack } from '../game-specific/cards-theme-name/effect-pack';
import { effectPack as cardsRitualPhasesEffectPack } from '../game-specific/cards-ritual-phases/effect-pack';
import { effectPack as boardPropertyEconomyEffectPack } from '../game-specific/board-property-economy/effect-pack';
import { effectPack as choiceAnonymousVoteEffectPack } from '../game-specific/choice-anonymous-vote/effect-pack';
import { effectPack as cardsSharedPrestigeEffectPack } from '../game-specific/cards-shared-prestige/effect-pack';
import { effectPack as cardsBattleTiesEffectPack } from '../game-specific/cards-battle-ties/effect-pack';
import { effectPack as choiceSimultaneousQuizEffectPack } from '../game-specific/choice-simultaneous-quiz/effect-pack';
import { effectPack as boardPathWallsEffectPack } from '../game-specific/board-path-walls/effect-pack';
import { effectPack as choiceStoryChallengeEffectPack } from '../game-specific/choice-story-challenge/effect-pack';
import { effectPack as cardsDiscardPenaltyEffectPack } from '../game-specific/cards-discard-penalty/effect-pack';
import { effectPack as cardsJudgedSubmissionEffectPack } from '../game-specific/cards-judged-submission/effect-pack';
import { effectPack as spatialGridPlacementEffectPack } from '../game-specific/spatial-grid-placement/effect-pack';
import { effectPack as boardMovementLandingsEffectPack } from '../game-specific/board-movement-landings/effect-pack';

/** Deterministic composition root. No filesystem discovery occurs at runtime. */
export const jsonEffectPacks = Object.freeze([
  raceMultiPawnEffectPack,
  raceEventCardsEffectPack,
  raceRouteDeliveryEffectPack,
  raceGooseTrackEffectPack,
  collectionTrackZonesEffectPack,
  raceResourceTrackEffectPack,
  raceTreasureTrackEffectPack,
  cardsOrderedParadeEffectPack,
  collectionFamilyRequestEffectPack,
  cardsOrderedAssemblyEffectPack,
  collectionMarketExchangeEffectPack,
  racePairedPawnsEffectPack,
  collectionThemedCirclesEffectPack,
  cardsPublicDomainEffectPack,
  raceProtectedHauntedTrackEffectPack,
  raceBidirectionalCollisionEffectPack,
  collectionFamilyEffectsEffectPack,
  raceTeamPawnCaptureEffectPack,
  raceQuizEventTrackEffectPack,
  raceBounceQuizEffectPack,
  collectionSpeciesTroopsEffectPack,
  raceDirectionalHazardsEffectPack,
  raceChainedTileCardsEffectPack,
  choiceChapterEncounterEffectPack,
  choiceSimultaneousPawScoringEffectPack,
  cardsThemeNameEffectPack,
  cardsRitualPhasesEffectPack,
  boardPropertyEconomyEffectPack,
  choiceAnonymousVoteEffectPack,
  cardsSharedPrestigeEffectPack,
  cardsBattleTiesEffectPack,
  choiceSimultaneousQuizEffectPack,
  boardPathWallsEffectPack,
  choiceStoryChallengeEffectPack,
  cardsDiscardPenaltyEffectPack,
  cardsJudgedSubmissionEffectPack,
  spatialGridPlacementEffectPack,
  boardMovementLandingsEffectPack,
] as const);

export type RegisteredJsonEffectPack = (typeof jsonEffectPacks)[number];
type EffectPacksByDomain = Readonly<
  Partial<Record<JsonEffectPackDomain, readonly RegisteredJsonEffectPack[]>>
>;
export const jsonEffectPacksByDomain: EffectPacksByDomain = (() => {
  const domains = new Map<JsonEffectPackDomain, RegisteredJsonEffectPack[]>();
  for (const pack of jsonEffectPacks) {
    const members = domains.get(pack.domain) ?? [];
    members.push(pack);
    domains.set(pack.domain, members);
  }
  return Object.freeze(
    Object.fromEntries(
      [...domains].map(([domain, packs]) => [domain, Object.freeze(packs)]),
    ),
  );
})();
