import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { CatPattesActionService } from './actions/cat-pattes-action.service';
import { CatPattesPresenterService } from './presenter/cat-pattes-presenter.service';
import { CatPattesSetupService } from './setup/cat-pattes-setup.service';
import { CatPattesBotService } from './bots/cat-pattes-bot.service';
export declare class CatPattesService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType = "cat-pattes";
    readonly category = "JeuxDePlateaux";
    readonly subcategory = "VentsDansants";
    readonly displayName: string;
    readonly description = "Course f\u00E9line jusqu\u2019\u00E0 1 000 pattes.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: CatPattesSetupService, actions: CatPattesActionService, presenter: CatPattesPresenterService, bots: CatPattesBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
