import type { GameStateEntity } from '../../../../core/entities/game-state.entity';
import type { GameSingleActionDto } from '../../../../engine/dto/game-action.dto';
import { GameCoreService } from '../../../../core/services/game-core.service';
import { RandomService } from '../../../../modules/random/services/random.service';
import { DeckPoliciesService } from '../../../../modules/deck-policies/services/deck-policies.service';
import { SacAMalicesSetupService } from '../setup/sac-a-malices-setup.service';
export declare class SacAMalicesActionService {
    private readonly random;
    private readonly core;
    private readonly setup;
    private readonly deckPolicies;
    constructor(random: RandomService, core: GameCoreService, setup: SacAMalicesSetupService, deckPolicies: DeckPoliciesService);
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    private applyVariantConfig;
    private handleRoll;
    private handleBuy;
    private handlePayFine;
    private handleUseJailCard;
    private openChooseProperty;
    private handleChooseProperty;
    private applyLanding;
    private drawAndApply;
    private applyCard;
    private drawCard;
    private moveForward;
    private moveTo;
    private sendToJail;
    private findJailTile;
    private findTileByName;
    private setPos;
    private setOwner;
    private setPot;
    private addSkip;
    private setJailTurns;
    private setGetOutOfJail;
    private setExtraRoll;
    private setConsecutiveDoubles;
    private advanceTurnOrExtraRoll;
    private getBuilding;
    private setBuilding;
    private getGroup;
    private isGroupComplete;
    private getMortgageValue;
    private getUnmortgageCost;
    private buildOne;
    private sellOne;
    private mortgageTile;
    private unmortgageTile;
    private loseOneInfrastructure;
    private addMoney;
    private releaseAssets;
    private setEliminated;
    private getPurchasePrice;
    private getRent;
    private advanceTurn;
    private checkWinner;
    private getMeta;
    private getRules;
    private pawnLabel;
}
