import type { GameStateEntity } from '../../../core/entities/game-state.entity';
import type { GameSingleActionDto, GameStateWithActions } from '../../../engine/dto/game-action.dto';
import { GameRegistryService } from '../../../engine/services/game-registry.service';
import { AbstractGameService } from '../../../engine/abstract/abstract-game.service';
import type { GameShortcutHint, GameShortcutsContext } from '../../../engine/shortcuts/game-shortcuts';
import { AbsurdissimesActionService } from './actions/les-absurdissimes-action.service';
import { AbsurdissimesBotService } from './bots/les-absurdissimes-bot.service';
import { AbsurdissimesPresenterService } from './presenter/les-absurdissimes-presenter.service';
import { AbsurdissimesSetupService } from './setup/les-absurdissimes-setup.service';
export declare class LesAbsurdissimesService extends AbstractGameService {
    private readonly setup;
    private readonly actions;
    private readonly presenter;
    private readonly bots;
    readonly gameType: "les-absurdissimes";
    readonly category = "Cartes";
    readonly subcategory = "VentsDansants";
    readonly displayName: string;
    readonly description = "Proposez les r\u00E9ponses les plus absurdes et convainquez le juge pour remporter la manche.";
    readonly minPlayers: number;
    readonly maxPlayers: number;
    constructor(registry: GameRegistryService, setup: AbsurdissimesSetupService, actions: AbsurdissimesActionService, presenter: AbsurdissimesPresenterService, bots: AbsurdissimesBotService);
    hydrateInitialState(baseState: GameStateEntity): GameStateEntity;
    applyActions(state: GameStateEntity, actions: GameSingleActionDto[]): GameStateEntity;
    getAvailableActions(state: GameStateEntity, playerId: number): GameSingleActionDto[];
    validateAction(state: GameStateEntity, action: GameSingleActionDto, actorId: number | null): GameSingleActionDto;
    exposeStateForUser(state: GameStateEntity, userId: number): GameStateWithActions;
    getBotActions(state: GameStateEntity, botPlayerId: number): GameSingleActionDto[];
    getShortcuts(ctx: GameShortcutsContext<any>): GameShortcutHint[];
}
